### ISSUE TITLE
SAM Bty (THAAD CEC), Not Enough Missiles

### ISSUE THREAD

**Issue by 5th-Domain** [PygmalionOfCyprus/cmo-db-requests#3682] opened 2023-08-09 16:22 UTC
### DB Selector

DB3K

### Affected DBID(s)

Facility #.3215 SAM Bty (THAAD CEC), United States, Army, 2019, 6x Launcher CEC

### Summary of Changes

Add a further 7x **Weapon #.3590 THAAD C-2 CEC** to each launcher as they should have 8x missiles each. In game DB3K v501 DB states this correctly but they only have one missile per launcher.

_"THAAD batteries have [four components](http://www.mda.mil/system/thaad.html): launcher, interceptors, radar, and fire control. Each battery can carry 48-72 interceptors (there are eight interceptors per launcher and typically each battery is believed to [contain six to nine launch vehicles](http://www.army-technology.com/projects/thaad/))."_ [1]

**File contains the unit already corrected if it save you time, currently saved as import/export file (.inst)**

[CMO Test File 39.zip](https://github.com/PygmalionOfCyprus/cmo-db-requests/files/12304706/CMO.Test.File.39.zip)

### Sources

[1] https://www.armscontrol.org/factsheets/usmissiledefense#:~:text=THAAD%20batteries%20have%20four%20components,from%20a%20truck%2Dmounted%20launcher.

**Comment by PygmalionOfCyprus** [comment] 2023-08-09 23:09
In the future please preface the DBIDs with their annex so I don't have to manually triage them.

**Comment by 5th-Domain** [comment] 2023-08-10 00:30
> In the future please preface the DBIDs with their annex so I don't have to manually triage them.

I'm not sure what that means.

**Comment by HunterDNiu** [comment] 2023-08-11 13:25
Dup #2683

**Comment by PygmalionOfCyprus** [comment] 2023-08-11 16:48
Duplicate of #2683

**Closed by PygmalionOfCyprus** 2023-08-11 16:48 UTC
Labels: DB3K, facility, update

**Comment by PygmalionOfCyprus** [comment] 2023-10-18 16:12
Yes.

**Comment by 5th-Domain** [comment] 2023-10-18 18:10
> Yes.

Excellent, thank you
