### ISSUE TITLE
CCG AOPV 43 Harry DeWolf

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#248] opened 2022-02-17 21:12 UTC
### DB Selector

DB3K

### Affected DBID(s)

#2797

### Summary of Changes

CORRECTIONS:
- Ship is part of Royal Canadian Navy, not the Coast Guard

ADD:
- SATCOM (Link 16)
- Kelvin Hughes SharpEye X and S-band navigation radars
- Vehicle bay; can hold pickup trucks, ATVs and snowmobiles (not sure if vehicle hold can be added or not

### Sources

https://en.wikipedia.org/wiki/Harry_DeWolf-class_offshore_patrol_vessel#Ships_in_class
https://www.tpsgc-pwgsc.gc.ca/app-acq/amd-dp/mer-sea/sncn-nss/arctique-coastgd-eng.html

![download](https://user-images.githubusercontent.com/99632305/154571374-a0782748-f1ae-450a-8494-7b5ab1b4ea53.jpg)

**Comment by tbrandon517** [comment] 2022-02-17 21:23
Duplicate of #147

**Comment by cdnice55** [comment] 2022-02-17 21:27
No, 147 is for the RCN version, this is for the Coast Guard version.

**Comment by PygmalionOfCyprus** [comment] 2022-02-25 08:45
Fixed for 493. Swapped out the generics for a Mk11 SharpEye (w/ X and S band radars) + a Scanter 6002 on both RCN and new CG versions and added Link 16.

**Closed by PygmalionOfCyprus** 2022-02-25 08:45 UTC
Labels: DB3K, ship, update
