### ISSUE TITLE
Add Fattah-1/2 Hypersonic missile

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#3997] opened 2023-11-19 14:06 UTC
### DB Selector

DB3K

### Baseline

Weapon 4221

### Hypothetical

No

### Name

Fattah-1, Fattah-2

### Length (m)

11.5

### Width/Span (m)

1

### Diameter (m)

0.8

### Weight (kg)

4600

### Range (nm)

750

### Warhead

500

### Targets

Land Structure - Soft, Land Structure - Hardened, Runway

### CEP (m)

4

### Sensors

None

### Weapon Codes

Bearing-Only Launch (BOL), Ballistic Missile or Rocket Booster, Weapon - INS w/ GNSS Navigation

### Comments

- Fattah-1`s payload is more to MaRV, rather than the one that have wide-body HGV which available for Fattah-2 as per recently unveiled pics. Fattah-2 should have HGV payload, while Fattah-1 will only have normal RV payload 
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99646926/0672213d-be3d-43ae-abbf-91204a71115c)
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99646926/10982670-cdaf-4920-8c1d-eaafbb3b377b)

- Unknown launcher type, but given that it were similarly sized to Kheibar Shekan(Weapon/4221), it probably can be launched from similar twin-rail launcher as well. Might be can copy Facility/3770 and replace the missile with Fattah-1/2  instead. 
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99646926/d8be823f-8e7f-424a-8fb0-d081422dc3ec)

- This hypersonic missile would be operated by IRGC Aerospace Force

### Sources

- https://twitter.com/Pataramesh/status/1726187648749080876
- https://english.iswnews.com/28711/military-knowledge-fattah-hypersonic-ballistic-missile/
- https://twitter.com/ProjectmeshkatE/status/1726199208842301802
- https://www.globalsecurity.org/wmd/world/iran/fattah.htm

**Comment by PygmalionOfCyprus** [comment] 2024-10-03 23:19
Duplicate of #4413, #4414

**Closed by PygmalionOfCyprus** 2024-10-03 23:19 UTC
Labels: addition, DB3K, weapon
