### ISSUE TITLE
China, PLAAA, Fire Snake 70/70A/GR5 Guided Rocket

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#4436] opened 2024-03-22 07:26 UTC
### DB Selector

DB3K

### Baseline

weapon 2597

### Hypothetical

No

### Name

Fire Snake 70 [FS 70, 70A, GR5]

### Length (m)

-

### Width/Span (m)

-

### Diameter (m)

-

### Weight (kg)

-

### Range (nm)

0.8-2.7

### Warhead

-

### Targets

Surface Vessel, Land Structure - Soft, Land Structure - Hardened, Mobile Target - Soft, Mobile Target - Hardened

### Sensors

1x Laser Spot Tracker

### Sources

https://twitter.com/jesusfroman/status/1442379548079755270
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/107970049/bf3809dd-b61b-4bbb-9765-352f7e2402b6)
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/107970049/b6ef3c22-1dac-48c0-abb2-574e9abe922f)

**Comment by PygmalionOfCyprus** [comment] 2024-09-27 19:27
Duplicate of #4948

**Closed as not planned by PygmalionOfCyprus** 2024-09-27 19:27 UTC
Labels: addition, DB3K, weapon
