### ISSUE TITLE
Please add Shahed-136 to Iran and Houti forces

### ISSUE THREAD

**Issue by Huib18** [PygmalionOfCyprus/cmo-db-requests#337] opened 2022-02-20 18:26 UTC
### DB Selector

DB3K

### Baseline

#2620 Harop

### Hypothetical

No

### Name

Shahed-136for Iran. Or Waeed for the Houti's

### Country

Iran

### Service

Iran and Houti forces in Yemen

### In Commission

2021

### Length (m)

See #2620 Harop

### Wingspan (m)

See #2620 Harop

### Height (m)

See #2620 Harop

### Empty Weight (kg)

See #2620 Harop

### Maximum Takeoff Weight (MTOW) (kg)

See #2620 Harop

### Payload Weight (kg)

See #2620 Harop

### Crew

Unmanned

### Propulsion

The engine mentioned is the Chinese engine MDR-208 or the Iranian copy of this which has a power of 38 bhp ( 28 kw ) at 7800 rpm, Specific Fuel Consumption .......................... 0.57 Ib/bhp/hr at max power, 0.52 Ib/bhp/hr at cruise.

### Rate of Climb (ft/min)

See #2620 Harop

### Service Ceiling (ft)

See #2620 Harop

### Military/Afterburner Speed (kt)

See #2620 Harop

### Cruise Speed (kt)

See #2620 Harop

### Supercruise

No

### Ferry Range (nm)

Not applicable

### Endurance (min)

range of 1240 to 1370 miles

### Takeoff / Landing Distance (m)

Catapult launched and lands with parachute.

### Sensors

No EO sensor visible.
Possibly pre-programmed/planned only

### Mounts

See #2620 Harop

### Loadout Options

See #2620 Harop

### Comms/Datalinks

Only very small antennas visible, I'm not sure. what do you think?
See:
https://pbs.twimg.com/media/FHemoAGXIAMemc2?format=jpg&name=large

### Aircraft Codes

Night Navigation (Ferry, Air-to-Air, Air-to-Surface Missiles), Night Navigation/Attack (Incl. Bomb, Rocket Delivery), Bombsight - Advanced Navigation (INS/GPS)

### Comments

It attacked probably the Saudi oil structures of aramco, and the M/T Mercer street. 

### Sources

https://twitter.com/OmniPresentEyes/status/1474876096692715521
https://twitter.com/FeWoessner/status/1474646971457675267
https://www.thedrive.com/the-war-zone/41871/everything-we-just-learned-about-the-fatal-iranian-drone-attack-on-a-tanker
https://www.jpost.com/middle-east/article-689785?utm_source=dlvr.it&utm_medium=twitter
https://www.newsweek.com/suicide-drones-linked-iran-have-made-their-way-yemen-rebels-photos-suggest-1628204
https://twitter.com/mhmiranusa/status/1436449773712781315
https://twitter.com/mhmiranusa/status/1474743337215213570
https://twitter.com/heartless_8080/status/1474413696537538564/photo/3
https://pbs.twimg.com/media/E-9QOa2XoBUSirf?format=jpg&name=small

**Comment by PygmalionOfCyprus** [comment] 2022-10-07 23:08
Duplicate of #2214

**Closed by PygmalionOfCyprus** 2022-10-07 23:08 UTC
Labels: addition, aircraft, DB3K
