### ISSUE TITLE
France - Mistral 3

### ISSUE THREAD

**Issue by nuk92** [PygmalionOfCyprus/cmo-db-requests#1222] opened 2022-05-26 14:32 UTC
### DB Selector

DB3K

### Hypothetical

No

### Name

SAM Plt (Mistral ATLAS)

### Facility Type

SAM

### Country

France

### In Commission

2020

### Sensors

1x Mk1 Eyeball
4x Matis MP3 [FLIR]

### Mounts

4x Mistral ATLAS (2x Mistral 3)

### Magazines

Mistral ATLAS 6x Mistral 3

### Comments

The Mistral 3 manpads should have the ability to engage missiles since it has an imaging IR seeker for targets with low ir signature.

### Sources

https://www.armyrecognition.com/defense_news_october_2020_global_security_army_industry/french_army_fires_its_first_mbda_mistral_3_surface-to-air_missiles.html

Matis:
https://poadu.wordpress.com/page/11/?archives-list=1

**Comment by PygmalionOfCyprus** [comment] 2022-05-27 00:47
Duplicate of #593

**Comment by PygmalionOfCyprus** [comment] 2022-05-27 09:08
No, never mind, this was for ATLAS and not just a standard MANPADS.

**Comment by PygmalionOfCyprus** [comment] 2022-05-27 09:15
Added 495.

**Closed by PygmalionOfCyprus** 2022-05-27 09:15 UTC
Labels: addition, DB3K, facility
