### ISSUE TITLE
Please add BVR capability for SU-25TM(SU-39)

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#415] opened 2022-02-27 15:56 UTC
### DB Selector

DB3K

### Affected DBID(s)

4445 SU-25TM Frogfoot C [SU-39]

### Summary of Changes

As per sources on the internet, the Su-25TM do have BVR capability via R-77 and Kopyo radar pod that can be carried underneath of the aircraft. As per Airvectors.net, "The Kopyo was a sophisticated radar system, originally developed for MiG-21 upgrades; it had navigation, air-to-ground, and maritime warfare modes, as well as air-to-air modes that allowed the Su-25TM to control "beyond visual range (BVR)" AAMs, though that would be a somewhat peculiar store for a close-support aircraft.". Please add 1x Kopyo radar pod and with at least 2x R-77 alongside 2x R-73.

Below is the pics of the aircraft with R-77 and Kopyo radar pod:
![image](https://user-images.githubusercontent.com/99646926/155889543-072ab034-aff3-425b-86da-44a75e80b2d2.png)

![image](https://user-images.githubusercontent.com/99646926/155889530-da3deade-c66c-461a-a378-fe252a01b589.png)

### Sources

http://www.airvectors.net/avsu25.html
https://www.key.aero/forum/modern-military-aviation/3782-bvr-air-to-air-missiles-on-su-25-39-it-s-strange
https://www.globalsecurity.org/military/world/russia/su-39.htm

**Comment by KLABDB3K** [comment] 2022-02-27 22:53
This has been requested under a different heading already.

**Comment by PygmalionOfCyprus** [comment] 2022-02-27 23:51
Duplicate of #265

**Closed by PygmalionOfCyprus** 2022-02-27 23:51 UTC
Labels: duplicate, DB3K, update
