### ISSUE TITLE
Increase docked boat size and capacity on Ship 2684 T-ESB 1 Lewis B. Puller

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#3611] opened 2023-07-17 23:44 UTC
### DB Selector

DB3K

### Affected DBID(s)

Ship 2684

### Summary of Changes

I wasn't able to load a CCM onto the ESB. It can do it. See links below. There is a lot of space below deck and looks like cranes/winches on both and first link . Navsea link says the cranes can support up to 10 metric tons.

Add a docking facility that can support 2-3 a 19m boats and probably safe. ESB has a 50m beam

### Sources

https://www.alamy.com/souda-bay-greece-may-17-2021-sailors-help-onload-a-combatant-craft-assault-craft-cca-onto-the-mission-deck-aboard-the-expeditionary-sea-base-uss-hershel-woody-williams-esb-4-in-souda-bay-greece-may-17-2021-hershel-woody-williams-is-on-a-scheduled-deployment-in-the-us-sixth-fleet-area-of-operations-in-support-of-us-national-interests-and-security-in-europe-and-africa-image442367470.html

https://www.alamy.com/souda-bay-greece-may-17-2021-boatswains-mate-seaman-samuel-martyka-uses-a-forklift-to-transport-a-combatant-craft-assault-craft-cca-across-the-mission-deck-aboard-the-expeditionary-sea-base-uss-hershel-woody-williams-esb-4-in-souda-bay-greece-may-17-2021-hershel-woody-williams-is-on-a-scheduled-deployment-in-the-us-sixth-fleet-area-of-operations-in-support-of-us-national-interests-and-security-in-europe-and-africa-image442367454.html

https://youtu.be/J157Au2ypLU?t=55
https://www.defensedaily.com/navy-tests-mcm-esb-4/navy-usmc/

**Comment by PygmalionOfCyprus** [comment] 2023-07-20 17:21
The LBP actually already has two LCVP davits in the DB, the problem is that the CCMs are not marked as being loadable into a davit (they require a pier). I've changed it so that they can "dock" in LCVP-sized davits.

**Closed by PygmalionOfCyprus** 2023-07-20 17:21 UTC
Labels: DB3K, ship, update
