### ISSUE TITLE
China, PLAGF, PCH-191 MLRS

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#1979] opened 2022-08-07 10:20 UTC
### DB Selector

DB3K

### Hypothetical

No

### Name

PCH-191 MLRS

### Facility Type

Arty

### Country

China

### Service

Army

### In Commission

2019

### Number in Service

20+

### Dispersion Radius (m)

80

### Sensors

1x Mk1 Eyeball

### Mounts

6x PHL-16 MLRS (Each of 8x BRE6 370mm Rocket /2x BRE8 750mm ballistic missile)

### Magazines

24x BRE8 750mm ballistic missile
144x 370mm BRE6 Rocket

### Sources

https://en.wikipedia.org/wiki/PHL-16
https://twitter.com/snekotron/status/1528214976195878912

**Comment by LuigiP57** [comment] 2022-08-07 10:23
#1977 #1976

**Comment by bostonmyk** [comment] 2023-12-01 18:41
https://twitter.com/Nickatgreat1220/status/1655568829123051530

**Comment by PygmalionOfCyprus** [comment] 2024-06-17 22:40
Duplicate of #988

**Closed by PygmalionOfCyprus** 2024-06-17 22:40 UTC
Labels: addition, DB3K, facility
