### ISSUE TITLE
F-35 CBU-105 WCMD Loadout

### ISSUE THREAD

**Issue by tksfpj** [PygmalionOfCyprus/cmo-db-requests#2687] opened 2022-12-17 08:02 UTC
### DB Selector

DB3K

### User(s)

USAF F-35A 2017-, USN F-35B 2016- USN F-35C 2019- ROKAF F-35A

### Weapons Carried

(Internal)
2 X AIM-120D AMRAAM
2X CBU-105 WCMD

### Requires Buddy Illumination

No

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Comments

CBU-105 WCMD integrated into F-35 from blk 3F

### Sources

https://www.dsca.mil/press-media/major-arms-sales/republic-korea-cbu-105db-sensor-fuzed-weapons

https://www.thedrive.com/the-war-zone/8967/miniature-smart-bombs-could-help-give-the-f-35-firepower-it-desperately-needs

![205476529-5c6c2d01-c8c5-4578-af3c-de2c090da0a7](https://user-images.githubusercontent.com/120775808/208232133-d44464fd-a82b-4635-bd7f-6d6e6604e200.jpg)

**Comment by FrangibleCover** [comment] 2022-12-19 20:49
Exact duplicate of #2633

**Comment by PygmalionOfCyprus** [comment] 2023-06-13 18:42
Duplicate of #2633

**Closed by PygmalionOfCyprus** 2023-06-13 18:42 UTC
Labels: DB3K, loadout
