### ISSUE TITLE
AIM-120D3 AMRAAM (Replace AIM-120D P3I.4 with this?)

### ISSUE THREAD

**Issue by KJohnston11** [PygmalionOfCyprus/cmo-db-requests#3180] opened 2023-03-13 02:50 UTC
### DB Selector

DB3K

### Baseline

51, 3413

### Hypothetical

No

### Name

AIM-120D3 AMRAAM SIP-4F

### Length (m)

3.66

### Width/Span (m)

0.45

### Diameter (m)

0.18

### Weight (kg)

150

### Range (nm)

108

### Target Altitude / Depth (ft)

30ft AGL - 80,000ft ASL

### Target Speed (kts)

0 kts - 1,950 kts 

### Launch Altitude / Depth (ft)

200ft AGL - 65,000ft ASL

### Warhead

18kg Blast-Frag - WDU-41/B

### Targets

Aircraft, Helicopter, Missile

### Sensors

1x Active Radar Seeker (Early 2020s Technology)

### Weapon Codes

Home On Jam (HOJ), Anti-Air All-Aspect, Capable vs Seaskimmer, Lock-On After Launch (LOAL) - CEC-Capable, Weapon - INS w/ GNSS Navigation, Uses GPS, Level Cruise Flight

### Comments

The AIM-120D3 doesn't get range out of better booster performance- it gets it out of better trajectory shaping and flight paths combined with lighter components. 

### Sources

https://aviationweek.com/defense-space/missile-defense-weapons/weekly-debrief-does-raytheons-new-aim-120d3-beat-chinas-best

https://www.airandspaceforces.com/air-force-successfully-tests-redesigned-amraam-aim-120d3/

https://aviationweek.com/shownews/farnborough-airshow/raytheon-fires-first-aim-120d3-missile-seeking-big-range-boost

https://www.iiss.org/blogs/military-balance/2022/09/analysis-air-to-air-warfare-speed-kills

**Comment by LuigiP57** [comment] 2023-03-13 04:53
But does the present AIM-120D P3I.4 refer to AIM-120C-8？AIM-120D-3, IMO, should be a new weapon, not a replacement.

**Comment by tbrandon517** [comment] 2023-03-13 09:18
Duplicate of #166

**Comment by KJohnston11** [comment] 2023-03-14 21:52
> Duplicate of #166

considering its from over a year ago- is there any reason why some entries here are left open without any action taken (not closed, not commented on, not approved, etc)?

**Comment by tbrandon517** [comment] 2023-03-14 22:10
> > Duplicate of #166
> 
> considering its from over a year ago- is there any reason why some entries here are left open without any action taken (not closed, not commented on, not approved, etc)?

Per the information on the main page for the Tracker.

"Anyone wishing for changes to the DB can post their request here.

Please note this is one of two trackers used by the DB team. (The other is private/internal.) Moreover, handling tickets is only one part of our DB workflow. Dev activity on this tracker will wax and wane as priorities shift; tickets will often be handled out-of-order in support of larger objectives.

While it can be frustrating to see your carefully-researched ticket languishing while others are handled out-of-turn, remember everyone is working towards the same goal: a comprehensive, accurate, and up-to-date database."

**Comment by KJohnston11** [comment] 2023-03-15 21:18
> > > Duplicate of #166
> > 
> > 
> > considering its from over a year ago- is there any reason why some entries here are left open without any action taken (not closed, not commented on, not approved, etc)?
> 
> Per the information on the main page for the Tracker.
> 
> "Anyone wishing for changes to the DB can post their request here.
> 
> Please note this is one of two trackers used by the DB team. (The other is private/internal.) Moreover, handling tickets is only one part of our DB workflow. Dev activity on this tracker will wax and wane as priorities shift; tickets will often be handled out-of-order in support of larger objectives.
> 
> While it can be frustrating to see your carefully-researched ticket languishing while others are handled out-of-turn, remember everyone is working towards the same goal: a comprehensive, accurate, and up-to-date database."

Oh yeah, I read the main page, but im more wondering what the process is behind which ones are admitted and which aren't

**Comment by PygmalionOfCyprus** [comment] 2023-06-06 18:23
Handled 501 along with dupe issues.

**Closed** 2023-06-06 18:28 UTC
Labels: addition, DB3K, weapon
