### ISSUE TITLE
Add OFZAB-500 500kg High-Explosive/Incendiary/ Fragmentation Bomb

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#1404] opened 2022-06-20 22:44 UTC
### DB Selector

DB3K

### Baseline

843

### Hypothetical

No

### Name

OFZAB-500

### Length (m)

2.385

### Width/Span (m)

.50

### Diameter (m)

,45

### Weight (kg)

500

### Range (nm)

1nm

### Launch Altitude / Depth (ft)

2953-39370 ft

### LaunchSpeed (kts)

297-999 knts

### Warhead

Incendiary bomblets

### Targets

Surface Vessel, Land Structure - Soft, Mobile Target - Soft, Mobile Target - Personnel

### CEP (m)

50m

### Sensors

none

### Comments

Used heavily in Ukraine War

### Sources

https://twitter.com/GuyPlopsky/status/1538868949483671553
http://roe.ru/eng/catalog/aerospace-systems/air-bombs/ofzab-500/
https://twitter.com/whatismoo/status/1500575653766348807/photo/1
https://twitter.com/rockfish31/status/1501919051219542032/photo/1
https://twitter.com/citeam_en/status/1501901875494404107?lang=en

**Comment by nuk92** [comment] 2022-06-20 23:58
Copy of #1348
It's not a classic incendiary weapon but a thermobaric  one. The only source to get it right: The Ordnance Guide for Civilians in Ukraine, in my comment. It uses the same incendiary mixture as the thermobaric RPG-7 rocket and RPO-M.

However this is a good source that you posted with additional information which I haven't found when I made the request:
https://twitter.com/whatismoo/status/1500575653766348807/photo/1

**Comment by PygmalionOfCyprus** [comment] 2022-06-21 02:19
Duplicate of #1348

**Closed by PygmalionOfCyprus** 2022-06-21 02:19 UTC
Labels: addition, DB3K, weapon
