### ISSUE TITLE
Addition of Podlet-K1 Low Altitude Radar Facility (RU side)

### ISSUE THREAD

**Issue by ghost** [PygmalionOfCyprus/cmo-db-requests#116] opened 2022-02-15 06:38 UTC
### DB Selector

CWDB

### Hypothetical

No

### Name

48Ya6-K1 Podlet K1

### Sensor Generation

Early 2010s

### Sensor Capabilities

Air Search, Range Information, Altitude Information, Speed Information, Heading Information

### Sensor Codes

Identification Friend or Foe (IFF) [Side Info], Continuous Tracking Capability, Passive Electronically Scanned Array (PESA)

### Search/Track Frequencies

E Band (2-3 GHz) [Old S Band] 10-15 cm, F Band (3-4 GHz) [Old S Band] 7.5-10 cm

### Scan Interval (s)

5±0,5 or 10±0,5

### Target Altitude (ft)

36000-65000ft (estimated)

### Comments

PESA Low-altitude S-band early warning and acquisition radar designed to detect low-flying stealth targets and supplement short/medium/long range air defenses.

Max range of 300km (no rcs or altitude info given). 

360 degree scanning

### Sources

https://www.radartutorial.eu/19.kartei/02.surv/karte040.en.html

https://roe.ru/eng/catalog/air-defence-systems/radar-and-electro-optical-equipment-for-air-target-detection/%22Podlet-E%22%20%2848YA6-K1E%29/

https://twitter.com/ralee85/status/1359929147766800385

**Comment by PygmalionOfCyprus** [comment] 2022-02-15 07:15
Duplicate of #8

**Closed by PygmalionOfCyprus** 2022-02-15 07:15 UTC
Labels: duplicate, addition, CWDB, sensor
