### ISSUE TITLE
F-117s Will Keep Flying At Least Until 2034

### ISSUE THREAD

**Issue by jun5896** [PygmalionOfCyprus/cmo-db-requests#2790] opened 2023-01-10 23:15 UTC
### DB Selector

DB3K

### Affected DBID(s)

F-117A Night Hawk

### Summary of Changes

- Change F-117A Nighthawk recommission status

Of the 59 F-117s built, the spokesperson confirmed that approximately 45 F-117s are currently in the inventory, with more than 10 already approved for transfer to museums.

### Sources

https://theaviationist.com/2023/01/10/f-117s-will-keep-flying-at-least-until-2034/amp/

https://www.thedrive.com/the-war-zone/retired-f-117-nighthawks-may-fly-for-another-decade

**Comment by tbrandon517** [comment] 2023-01-11 01:54
Related Request #1556

**Comment by PygmalionOfCyprus** [comment] 2023-03-09 22:10
Duplicate of #1556

**Closed by PygmalionOfCyprus** 2023-03-09 22:10 UTC
Labels: aircraft, DB3K, update
