### ISSUE TITLE
Fattah 1 MRBM

### ISSUE THREAD

**Issue by Siegemiester** [PygmalionOfCyprus/cmo-db-requests#4413] opened 2024-03-18 10:46 UTC
### DB Selector

DB3K

### Baseline

Pershing 2

### Hypothetical

No

### Name

Fattah 1

### Length (m)

11.5

### Width/Span (m)

1.2

### Diameter (m)

0.8

### Weight (kg)

4300kg

### Range (nm)

755

### Warhead

500kg HE

### Targets

Land Structure - Soft, Land Structure - Hardened, Runway - Radar - Mobile

### CEP (m)

10m

### Sensors

Inertial Guidance

### Weapon Codes

Bearing-Only Launch (BOL), Weapon - INS Navigation, Terminal Maneuver - Random (Advanced)

### Comments

Iranian medium range ballistic missile equipped with a MARV warhead produced in 2023, Likely limited to Inertial guidance against fixed targets only.

Warhead is expected to achieve a maximum speed of mach 13-15 and a terminal velocity of over mach 5.

MARV warhead specifically designed to overcome ABM systems employed by the US and Israel through terminal manoeuvres.

### Sources

https://english.iswnews.com/28711/military-knowledge-fattah-hypersonic-ballistic-missile/

https://en.wikipedia.org/wiki/Fattah-1_(missile)

**Comment by Siegemiester** [comment] 2024-10-02 10:23
Well. Its fully confirmed that this missile infact does exist, and works more or less as specified
https://www.msn.com/en-au/news/other/biden-orders-us-military-to-shoot-down-iran-s-salvo-of-ballistic-missiles-on-israel/ar-AA1rwXrU

**Comment by Luigi-II** [comment] 2024-10-02 11:24
duplicate of #3997

**Comment by PygmalionOfCyprus** [comment] 2024-10-15 19:16
Handled 509.

**Closed as completed by PygmalionOfCyprus** 2024-10-15 19:16 UTC
Labels: addition, DB3K, weapon
