### ISSUE TITLE
Mistral 3 manpads weapon entry

### ISSUE THREAD

**Issue by nuk92** [PygmalionOfCyprus/cmo-db-requests#1223] opened 2022-05-26 15:43 UTC
### DB Selector

DB3K

### Baseline

3890 - Mistral 3 director

### Hypothetical

No

### Name

Mistral 3 - (2019, MANPADS)

### Length (m)

-

### Width/Span (m)

-

### Diameter (m)

-

### Weight (kg)

-

### Range (nm)

4

### Target Altitude / Depth (ft)

13500

### Launch Altitude / Depth (ft)

-

### Warhead

-

### Targets

Aircraft, Helicopter, Missile

### Sensors

1x IR Seeker Mistral 3

### Comments

Most can be copied form the existing Mistral-3 director entry + the changes in my update request. The accuracy would be around 75%. And since it has an imaging ir seeker it is highly jamming resistant.

### Sources

https://www.mbda-systems.com/product/mistral-atlas/

**Comment by PygmalionOfCyprus** [comment] 2022-05-27 00:46
Duplicate of #591

**Closed by PygmalionOfCyprus** 2022-05-27 00:46 UTC
Labels: addition, DB3K, weapon
