### ISSUE TITLE
China - GB-500C(Sino-JSOW-ER)

### ISSUE THREAD

**Issue by yU2187sie** [PygmalionOfCyprus/cmo-db-requests#4513] opened 2024-05-01 06:17 UTC
### DB Selector

DB3K

### Baseline

JSOW-ER

### Hypothetical

No

### Name

GB-500C

### Length (m)

As JSOW-ER

### Width/Span (m)

As JSOW-ER

### Diameter (m)

As JSOW-ER

### Weight (kg)

500

### Range (nm)

189

### Target Altitude / Depth (ft)

As JSOW-ER

### Target Speed (kts)

As JSOW-ER

### Launch Altitude / Depth (ft)

As JSOW-ER

### LaunchSpeed (kts)

As JSOW-ER

### Warhead

240 individual submunitions

### Targets

Surface Vessel, Land Structure - Soft, Land Structure - Hardened, Runway, Mobile Target - Soft, Mobile Target - Hardened

### CEP (m)

2

### Sensors

1x IIR Seeker

### Weapon Codes

Bearing-Only Launch (BOL), Weapon - INS w/ GNSS Navigation, Uses BeiDou/COMPASS,Supports WayPoints,Flight Profile - Terrain Following,Home On Jam (HOJ),Level Cruise Flight

### Comments

According to the information displayed at various defense exhibitions at present, we have found a Tianlei500 based extended range ammunition. Based on the information on the ammunition we're calling it GB500C.
We speculate that this is a JSOW-ER product. The munition adds a turbojet engine to the Tianlei500, allowing it to fly after launch to increase its range so that the aircraft does not have to approach the enemy's SAM.
RCS  just same as weapon 3595
Speed: 520kt
A datalink is needed
Affected DBID: Aircraft 4905 5596 4926 6450 6098 4827 4828
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/130222813/1d4ea08a-9cc1-4662-9e84-09f8c2a26109)
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/130222813/6073c9de-d166-412a-a447-b71f39dab436)

### Sources

https://twitter.com/jesusfroman/status/1588587419162398720/photo/1
https://twitter.com/savunmaisleri/status/1588832675342655488/photo/1

**Comment by PygmalionOfCyprus** [comment] 2024-05-03 19:41
Is this actually in service with the PLA or is it just a new product being shown off?

**Comment by LuigiP57** [comment] 2024-05-04 01:40
> Is this actually in service with the PLA or is it just a new product being shown off?

![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/107970049/54a439a7-a7ac-478e-a4f9-da8c7122708a)

It's hard to believe that a single picture can tell us everything

**Comment by PygmalionOfCyprus** [comment] 2024-05-06 16:08
Right, I'm familiar. It doesn't appear in that photo, so my thought (GB6 is different AFAIK) was that it wasn't in service, but I wanted to ask before closing the ticket just in case the OP had some extra info.

**Comment by PygmalionOfCyprus** [comment] 2024-10-11 18:19
I'm still not convinced that this is actually in service with the PLA. It would make sense for it to be, and the barriers to integration are presumably lower since it's a variant of the GB-6 which _is_ confirmed in service. (Then again, maybe there is an obstacle re: datalink, etc. not present with the normal version?) But we haven't seen any indication that it is in service, nothing to separate it from all the other Norinco hopefuls. It would hardly be the first time that an "improved" version of a weapon in service is advertised but not actually adopted.

**Closed as not planned by PygmalionOfCyprus** 2024-10-11 18:19 UTC
Labels: addition, DB3K, weapon

**Comment by FRF312** [comment] 2024-10-30 05:59
@PygmalionOfCyprus It seems that PLAAF J-16 fighter has already loaded a GB-6 or GB-6 like weapon in 2016.3.
![87BF175162C25F3B12E3A4D570F3614D](https://github.com/user-attachments/assets/0397ccce-01be-47e4-845e-d79ae5683f1d)
![image](https://github.com/user-attachments/assets/309b3076-13b2-4230-8ab0-66e66e686933)
PLAAF J-8F has already launched it.
