### ISSUE TITLE
F/A-18E and F with four AIM-174A missiles

### ISSUE THREAD

**Issue by OrthodoxGraveMusical** [PygmalionOfCyprus/cmo-db-requests#5329] opened 2024-11-06 23:38 UTC
### DB Selector

DB3K

### User(s)

F/A-18E (7282, 7281) and F/A-18F (7284, 7283)

### Weapons Carried

4x AIM-174A
4x AIM-120D or AIM-260
2x Sidewinder missiles
1x Legion Pod

### Requires Buddy Illumination

No

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Comments

Probably two different loadouts. One for the AIM-120D and another for the AIM-260.

### Sources

https://www.twz.com/air/navy-posts-its-first-aim-174-missile-armed-f-a-18f-super-hornet-glamour-shots

**Comment by tbrandon517** [comment] 2024-11-07 01:02
Duplicate of #5062

**Comment by OrthodoxGraveMusical** [comment] 2024-11-07 01:10
Close to 5062

**Closed as completed** 2024-11-07 01:09 UTC
Labels: DB3K, loadout
