### ISSUE TITLE
India - Astra Mk I BVRAAM (2019)

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#1231] opened 2022-05-27 09:53 UTC
### DB Selector

DB3K

### Baseline

2056 AA-12 Adder B [R-77-1, RVV-SD] (2015, Izdeliye 170-1)

### Hypothetical

No

### Name

Astra Mk I

### Length (m)

3.57

### Width/Span (m)

0.178

### Diameter (m)

0.16

### Weight (kg)

154

### Range (nm)

43.2

### Launch Altitude / Depth (ft)

0-82021

### Warhead

15

### Targets

Aircraft, Helicopter, Missile

### Sensors

Ku-band Active Radar Seeker (derivates from the R77's 9B1103M Seeker)

### Weapon Codes

Anti-Air All-Aspect, Anti-Air Dogfight (High Off-Boresight), Lock-On After Launch (LOAL) - CEC-Capable

### Sources

_IHS Jane's. 2021. IHS Jane's Weapons Air-launched 2021-2022. Coulsdon, Surrey, UK: IHS Global._

![67](https://user-images.githubusercontent.com/35732829/170674176-077e25ee-6dd4-4d0e-be08-0b1cb9295bff.png)
![68](https://user-images.githubusercontent.com/35732829/170674180-aa3e85d3-c099-4bd3-8e28-7629dc27e927.png)
![69](https://user-images.githubusercontent.com/35732829/170674181-c439206a-92f5-4e3b-82da-78f038175e35.png)
![70](https://user-images.githubusercontent.com/35732829/170674183-43da1c7a-aee0-48a1-803e-b9eccd2f5cbd.png)

**Comment by PygmalionOfCyprus** [comment] 2022-05-27 10:02
Duplicate of #1065

**Comment by PygmalionOfCyprus** [comment] 2022-05-27 10:03
I'm going to close this ticket, but it's linked to the other one, so I'll use the info here when I tackle the OG issue.

**Closed by PygmalionOfCyprus** 2022-05-27 10:03 UTC
Labels: addition, DB3K, weapon

**Comment by claudejdev** [comment] 2022-05-27 12:02
Ouch, I must have FU my pre-request check. Sorry.
What's an "OG issue" by the way?

**Comment by PygmalionOfCyprus** [comment] 2022-05-27 13:43
"OG" is just an abbreviation for "original." So, the originally posted issue.

**Comment by claudejdev** [comment] 2022-06-03 17:36
> India’s MoD has signed an INR29.71 billion ($382.7 million) contract with state-owned Bharat Dynamics Limited (BDL) for an undisclosed number of indigenously developed Astra Mk.1 beyond-visual-range air-to-air missiles (BVRAAM) and associated equipment.
> 
> These missiles will arm Indian Air Force (IAF) [Su-30MKI](https://plus.shephardmedia.com/detail/su-30/?_ga=2.238171136.1831032807.1653940465-1832268661.1653007695) and Indian Navy [MiG-29K](https://plus.shephardmedia.com/detail/mig-29/?_ga=2.8133682.1831032807.1653940465-1832268661.1653007695)/KUB fighters.
> 
> Designed by the Defence Research and Development Organisation (DRDO), the Astra BVRAAMs have a 110km strike range.
> 
> Although the MoD declined to enumerate the quantity of Astras it had ordered on 31 May under the Indigenous Designed, Developed and Manufactured category of Defence Acquisition Procedure-2020, military sources put this number at around 200.

https://www.shephardmedia.com/news/air-warfare/india-orders-astra-air-to-air-missiles-from-bdl/
