### ISSUE TITLE
Quickstrike-ER 2000lb

### ISSUE THREAD

**Issue by HunterDNiu** [PygmalionOfCyprus/cmo-db-requests#2636] opened 2022-12-04 12:32 UTC
### DB Selector

DB3K

### Baseline

2089

### Hypothetical

Yes

### Name

Quickstrike-ER [2000lb]

### Length (m)

2.8

### Width/Span (m)

0.74

### Diameter (m)

0.53

### Weight (kg)

1086

### Range (nm)

0-40

### Target Altitude / Depth (ft)

Same as weapon 3103

### Target Speed (kts)

Same as weapon 3103

### Launch Altitude / Depth (ft)

Same as weapon 3103

### LaunchSpeed (kts)

Same as weapon 3103

### Warhead

Same as weapon 2089, or a weapon 2089. 

### Targets

Surface Vessel, Submarine

### CEP (m)

Same as weapon 3103

### Sensors

Same as weapon 2089

### Weapon Codes

Bearing-Only Launch (BOL), Uses GPS, Mine - Magnetic Fuze, Total-Field Magnetometer, Mine - Passive Acoustic Fuze, Narrow-Band (Advanced), Mine - Seismic Fuze, Mine - Delay Counter, Mine - Arming Delay, Mine - Target Discrimination / Identification, Level Cruise Flight

### Comments

Quickstrike-ER(QS-ER) combines mines with JDAM-ER kits to allow standoff, high-altitude release. 
This may require modeling the mine as a  payload of the guided weapon. 
Only 2000lb ones have been confirmed but 500lb are possible. 
Carriers of weapon 2089 shall be able to carry this at the same capacity. Also B-2s and B-21s. 
There is a Quickstrike-J variant, which pairs mine with a standard JDAM kit, having less range. 
The Navy has an unfunded program(QS-P) employing a powered wing kit to achieve even grater range. 

### Sources

https://www.thedrive.com/the-war-zone/23705/b-52-tested-2000lb-quickstrike-er-winged-standoff-naval-mines-during-valiant-shield
https://www.navalnews.com/naval-news/2019/06/u-s-indo-pacific-command-tests-quickstrike-er-naval-mine-from-b-52-bomber/
https://seapowermagazine.org/navy-orders-quickstrike-extended-range-glide-kits-for-sea-mines/
https://www.taxpayer.net/wp-content/uploads/2022/04/FY2023-UPL_Navy.pdf

**Comment by tbrandon517** [comment] 2022-12-04 17:36
Duplicate of #353

**Comment by PygmalionOfCyprus** [comment] 2023-06-13 18:42
Duplicate of #353

**Closed by PygmalionOfCyprus** 2023-06-13 18:42 UTC
Labels: addition, DB3K, weapon, hypo
