### ISSUE TITLE
Duplicate Entries

### ISSUE THREAD

**Issue by cdnice55** [PygmalionOfCyprus/cmo-db-requests#542] opened 2022-03-07 05:30 UTC
### DB Selector

DB3K

### Affected DBID(s)

2175&3509, 2013&3501, 1544&3502

### Summary of Changes

Appears to be duplicate entries, info looks the same, one has a picture and the other does not.

### Sources

DB3K: 2175&3509, 2013&3501, 1544&3502

**Comment by PygmalionOfCyprus** [comment] 2022-03-07 09:45
Duplicate of #460

**Closed by PygmalionOfCyprus** 2022-03-07 09:45 UTC
Labels: DB3K, update
