### ISSUE TITLE
PLARF, Launchers, Reloads, Organization

### ISSUE THREAD

**Issue by RickDNiu** [PygmalionOfCyprus/cmo-db-requests#5110] opened 2024-09-24 14:40 UTC
- Launchers

1. The DF-31 and DF-31A use towed trailers (need many support vehicles) and have no off-road capability (concrete pads etc). The DF-31AG utilizes mobile launchers and has off-road capability. (Note: this refers to the launchers only.)
2. The DF-26 should have a swappable launcher for ASBM.
3. 

- Reloads

1. Maintain a standard of two reloads. This is the basic capacity of a typical base, excluding considerations like tunnels or missile-carrying trucks reloading themselves after delivering a reload.  
2. Nuclear missiles should have no reloads, but reloads may be used to represent preparation time (e.g., from weapon allocation to firing, where the actual missile replaces a placeholder). This could have varying times to reflect different alert statuses, especially for the DF-5 (fueling, silo-based elevation, tunnel-based movement/erection), DF-31/31A (requiring specialized facilities for MEL loading, such as 24.3600017980225, 102.49082080519418), and DF-26. The DF-26, and to a certain extent DF-21, should have 1x reload to support swapping, particularly when using a swappable (not simply dual-capable) configuration.  
3. DF-27, DF-26, DF-17, DF-16 (A, B, only has G and B mag has G), DF-15 (A submunition) lack full or partial reloads.

- Organization

> To the best of our knowledge:

1. Each brigade (旅) typically operates one type of missile and consists of 6 launching battalions (營), each with 2 companies (排).  
2. Nuclear ICBM brigades have 2 launchers per battalion.  
4. SRBM/MRBM brigades operate 6 launchers per battalion, with each company containing three platoons (連), and one launcher per platoon. The IRBM (DF-26) likely follows this pattern.  
5. GLCM (CJ-10/10A) brigade garages are often organized in groups of 8 or 16 (e.g., Bde 618, 32 total: 28.501544933336856, 115.91906378118256, note the tire marks).  
6. DF-17 brigade garages are usually grouped in units of 5 or 10 (e.g., Bde 616, 90 total with 2/3 attached to the high bay (the high bay is found for both DF-17 and DF-26, attached garage is also found at DF-26 but with 6x/12x garages), note the bay doors: 25.90349154605201, 114.96110075495793).  
7. I suggest that launchers/reloads be implemented at the battalion level as is apparently now.

**Comment by PygmalionOfCyprus** [comment] 2024-09-30 18:31
I _think_ this is an improvement / duplicate of #4154 and #3550 from your old account...it's still shadowbanned, so I can't check, but since I can't open those tickets anyway I'll just close them and let this stand as the new PLARF tweak ticket.

**Comment by PygmalionOfCyprus** [comment] 2024-10-17 21:48
Mostly handled 509. Held off on giving the DF-26 units ASBM reloads because I'm not sure if the ASBM variant is issued to the same units that handle conventional? Could be totally wrong about that. Implemented the rest as requested except in cases where our research indicated otherwise for Bn launcher count.

**Closed as completed by PygmalionOfCyprus** 2024-10-17 21:48 UTC
Labels: DB3K, facility, update, blob
