### ISSUE TITLE
Add 9M96E2 and 9M96 missiles to S400

### ISSUE THREAD

**Issue by TTZ32** [PygmalionOfCyprus/cmo-db-requests#667] opened 2022-03-13 21:44 UTC
### DB Selector

DB3K

### Affected DBID(s)

S-400 

### Summary of Changes

S-400 TELs can be equipped with both 9M96 and 9M96E2 missiles.

### Sources

![images - 2022-03-14T083938 437](https://user-images.githubusercontent.com/99824301/158080366-76090867-89f5-4c32-a09b-5fa9fa1c886c.jpeg)
![images - 2022-03-14T083950 471](https://user-images.githubusercontent.com/99824301/158080373-f29a8d72-f78a-4b35-8cf9-66a10edfefed.jpeg)
https://www.army-technology.com/projects/s-400-triumph-air-defence-missile-system/

**Comment by KLABDB3K** [comment] 2022-03-14 00:10
These are air show PR photos. The 9M96 didn't work properly until 2018/2019 which is why the Gorshkov took so long to commission. Photos of operational units with the quad pack haven't yet started emerging but Turkish S-400 troops training in Russia were shown with a 9M96 quad pack in 2020. It has been requested several times before. 
![Screenshot_20220314-000912_Keep Notes](https://user-images.githubusercontent.com/99494755/158085504-3c7e126f-4926-452b-97e8-26daecc755c0.jpg)

**Comment by TTZ32** [comment] 2022-03-14 06:26
> These are air show PR photos. The 9M96 didn't work properly until 2018/2019 which is why the Gorshkov took so long to commission. Photos of operational units with the quad pack haven't yet started emerging but Turkish S-400 troops training in Russia were shown with a 9M96 quad pack in 2020. It has been requested several times before. ![Screenshot_20220314-000912_Keep Notes](https://user-images.githubusercontent.com/99494755/158085504-3c7e126f-4926-452b-97e8-26daecc755c0.jpg)

Regardless of that,

**Comment by KLABDB3K** [comment] 2022-03-14 16:59
It doesnt need to be hypothetical it just needs to have an accurate in service date. The Russian S400 batteries are dated from 2008 and 2017 both before the 9M96 actually worked,it just needs an in service date from 2019 and the S-350 Vityaz also needs a revised date as it wasnt declared operational until circa 2020 not 2017. Its a can of worms with Russian systems as stuff as advertised long before it is actually working.

**Comment by bostonmyk** [comment] 2022-03-14 18:04
Duplicate issues

https://github.com/PygmalionOfCyprus/cmo-db-requests/issues/90

**Comment by PygmalionOfCyprus** [comment] 2022-03-17 05:45
Confirmed duplicate of #90

**Closed** 2022-03-17 05:46 UTC
Labels: duplicate, DB3K, facility, update

**Comment by bostonmyk** [comment] 2022-07-02 13:14
https://twitter.com/GuyPlopsky/status/1543135981490302978
