### ISSUE TITLE
DPRK IL-28/H-5

### ISSUE THREAD

**Issue by trevor99999** [PygmalionOfCyprus/cmo-db-requests#1983] opened 2022-08-08 17:46 UTC
### DB Selector

Both

### Baseline

IL-28/H-5

### Hypothetical

No

### Name

H-5

### Country

DPRK

### Service

Korean People's Army Air and Anti-Air Force

### In Commission

1953

### Number in Service

20 ? 80 ?

### Length (m)

17.65

### Wingspan (m)

21.45

### Height (m)

6.7

### Empty Weight (kg)

12890

### Maximum Takeoff Weight (MTOW) (kg)

21200

### Payload Weight (kg)

1000 - 3000

### Crew

3

### Propulsion

2 × Klimov VK-1A centrifugal-flow turbojet engines

### Rate of Climb (ft/min)

3000

### Service Ceiling (ft)

40400

### Military/Afterburner Speed (kt)

487

### Cruise Speed (kt)

420

### Supercruise

No

### Ferry Range (nm)

unknown (1180 nm range)

### Endurance (min)

unknown

### Takeoff / Landing Distance (m)

unknown

### Fuel Capacity (kg)

unknown

### Sensors

unknown

### Mounts

unknown

### Loadout Options

Guns: 4 × Nudelman-Rikhter NR-23 cannons (2 in nose and 2 in tail) ?
Bombs: 3,000 kg (6,600 lb) of bombs in internal bay (1,000 kg (2,200 lb) normal)

### Comms/Datalinks

unknown

### Comments

Last operator of the IL-28/H-5

### Sources

https://en.wikipedia.org/wiki/Korean_People%27s_Army_Air_and_Anti-Air_Force#Current_inventory
https://en.wikipedia.org/wiki/Ilyushin_Il-28#Chinese_variants
http://www.combataircraft.com/en/Military-Aircraft/Ilyushin/IL-28-Beagle/
https://www.aeroflight.co.uk/user/fleet/north-korea-af-ilyushin-il-28-beagle.htm
https://www.iiss.org/blogs/military-balance/2021/06/north-korea-air-force-inventory

**Comment by tbrandon517** [comment] 2022-08-08 19:23
Duplicate of #711 #712 #714 #719

**Closed** 2023-06-13 18:44 UTC
Labels: addition, aircraft, CWDB, DB3K
