### ISSUE TITLE
Karrar UCAV consume too much fuel at MIL speed

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#3473] opened 2023-06-14 11:06 UTC
### DB Selector

DB3K

### Affected DBID(s)

Aircraft 4904, 4903, 5591, 6429

### Description of Problem

Aircrafts consumed too much fuel at MIL speed compared to BQM-167A Skeeter(Aircraft/5281), which used Microturbo TRI-60 (what Toloue-4 engine is based on). Both should have similar fuel consumption

BQM-167A Skeeter`s fuel consumption
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99646926/01a9552d-a983-4f14-915f-579f1424533d)

HESA Karrar`s fuel consumption
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/99646926/49ad6f86-aad9-44dc-a51b-5b32d1775a20)

### Recommended Fix

Make HESA Karrar`s (Aircraft 4904, 4903, 5591 & 6429) fuel consumption similar to BQM-167A Skeeter(Aircraft/5281)

**Comment by PygmalionOfCyprus** [comment] 2023-07-12 20:58
Duplicate of #3582

**Closed by PygmalionOfCyprus** 2023-07-12 20:58 UTC
Labels: bug, aircraft, DB3K, update
