### ISSUE TITLE
Jiangkai II SAM Datalinks-SAMS Can't Fire

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4199] opened 2024-01-25 15:44 UTC
### DB Selector

DB3K

### Affected DBID(s)

All Jiangkai II

### Summary of Changes

Make sure Radar and Missile datalinks match up.

### Sources

Attached Scenario. A lot of units get smacked before they can legally fire due to OODA, but you should be able to see with a couple that you get datalink errors once they clear the OODA restriction.

**Comment by bostonmyk** [comment] 2024-01-25 16:01
[Jiangkai SSM2.zip](https://github.com/PygmalionOfCyprus/cmo-db-requests/files/14054425/Jiangkai.SSM2.zip)

**Comment by bostonmyk** [comment] 2024-01-25 16:57
Ah update Pakistani Jiangkai II to match when ready.

**Comment by PygmalionOfCyprus** [comment] 2024-01-25 21:44
Duplicate of #4172

**Closed by PygmalionOfCyprus** 2024-01-25 21:44 UTC
Labels: DB3K, update
