### ISSUE TITLE
Fuel Consumption Hermes UAV

### ISSUE THREAD

**Issue by Quark-73** [PygmalionOfCyprus/cmo-db-requests#3031] opened 2023-02-14 18:25 UTC
### DB Selector

DB3K

### Affected DBID(s)

aircraft #5645, #5323, #5324, #4646, #5413, #5102, #5330, #5811, #5892,  #2576

### Summary of Changes

Same issue like in #2968 with MQ-8B Drone lowest fuel consumption is on max. speed. There seems to be a systematic failure.

### Sources

I have no source but it was was fine some versions ago.

**Comment by Quark-73** [comment] 2023-02-15 07:23
Is it possible for regular users to label issues?

**Comment by K1l0tangoDef3nce** [comment] 2023-02-15 08:52
This issue has already been handled for the next DB update
https://github.com/PygmalionOfCyprus/cmo-db-requests/issues/2569

**Comment by PygmalionOfCyprus** [comment] 2023-02-15 17:34
Duplicate of #2569

**Closed by PygmalionOfCyprus** 2023-02-15 17:34 UTC
Labels: aircraft, DB3K, update
