### ISSUE TITLE
type 093B Increase VLS from 8 to 18

### ISSUE THREAD

**Issue by Siegemiester** [PygmalionOfCyprus/cmo-db-requests#5243] opened 2024-10-16 09:14 UTC
### DB Selector

DB3K

### Affected DBID(s)

665

### Summary of Changes

Recent OSINT news has reported that the Type 093B actually incorporates alot more features planned for the Type 095 

![006Gzorxgy1hujt44u6nej30ue14itbw-2](https://github.com/user-attachments/assets/4cc674eb-b9ad-476a-8434-3fc3efd2364d)

Namely  "an 18-unit arrangement in a 6×3 layout," VLS that was previously believed to be part of the Type 095 project.

https://www.china-arms.com/2024/06/type-093b-and-type-054b/

https://armyrecognition.com/news/navy-news/2024/china-unveils-new-6-200-ton-type-093b-nuclear-submarine-model-with-18-vertical-launch-units

### Sources

https://www.navalnews.com/naval-news/2024/10/chinese-type-09iiib-nuclear-powered-submarine-surfaces-in-image/

https://www.china-arms.com/2024/06/type-093b-and-type-054b/

https://armyrecognition.com/news/navy-news/2024/china-unveils-new-6-200-ton-type-093b-nuclear-submarine-model-with-18-vertical-launch-units

**Comment by Luigi-II** [comment] 2024-10-16 16:12
duplicate of #4762 and some valid source claims it has 24 cells of VLS.

**Comment by Luigi-II** [comment] 2024-10-16 16:14
https://www.navalnews.com/naval-news/2024/10/chinese-type-09iiib-nuclear-powered-submarine-surfaces-in-image/#prettyPhoto

> A related variation of this SSN design appeared in[ a video presentation of the Harbin Engineering University](https://www.bilibili.com/video/BV1rp4y1E752/) in August 2023. A graphic of the design on a wall in the University exhibition showed an overall identical SSN. The major distinction of the boat is a visible VLS-row of eight launchers. The number of rows is not clearly visible but may suggest up to 24 launchers for VLS-ordnance.

**Comment by PygmalionOfCyprus** [comment] 2024-10-16 21:20
Duplicate of #4762

**Closed as not planned by PygmalionOfCyprus** 2024-10-16 21:20 UTC
Labels: DB3K, update
