### ISSUE TITLE
China, Large synthetic impulse and aperture radar (SIAR),An OTH radar

### ISSUE THREAD

**Issue by yUsie108** [PygmalionOfCyprus/cmo-db-requests#4946] opened 2024-08-25 08:52 UTC
### DB Selector

DB3K

### Baseline

Sensor 5649

### Hypothetical

No

### Name

China SIAR

### Sensor Generation

Late 2010s

### Range (nm)

10-1500

### Sensor Capabilities

Air Search, Range Information, Altitude Information, Speed Information, Heading Information,OTH (Backscatter)

### Sensor Codes

Identification Friend or Foe (IFF) [Side Info], Classification [Class Info] / Brilliant Weapon [Automatic Target Acquisition], Moving Target Indicator (MTI), Pulse Doppler Radar (Full LDSD Capability), Active Electronically Scanned Array (AESA)

### Search/Track Frequencies

A Band (30-250 MHz) [Old P Band (HF)] 100-300 cm

### Scan Interval (s)

10

### Target Altitude (ft)

0-100000ft

### Horizontal Beamwidth (deg)

1

### Vertical Beamwidth (deg)

1

### System Noise Level (dB)

3

### Processing Gain/Loss (dB)

10

### Peak Power (W)

7000000

### Pulse Width (μs)

0.16

### Blind Time (μs)

0.4

### PRF (Hz)

30

### Comments

According to satellite images released as early as 2016, the PLA has installed SIAR at its bases in the South China Sea to monitor the air posture of neighboring countries. The analysis believes that the radar works in the 100mhz-200mhz band, the purpose is to effectively monitor the stealth fighters of various countries.
In response to the United States' powerful stealth technology, China's use of this unique new radar as a counter measure is worth keeping track of.

### Sources

https://news.usni.org/2016/02/22/new-possible-chinese-radar-installation-on-south-china-sea-artificial-island-could-put-u-s-allied-stealth-aircraft-at-risk
https://www.popularmechanics.com/military/weapons/news/a19602/china-installing-anti-stealth-radar-in-south-china-sea/
![image](https://github.com/user-attachments/assets/772d5da0-a850-46dd-a195-8f48a61b11e1)
![image](https://github.com/user-attachments/assets/a0ef1b7d-9542-43b2-bd5c-580304ef20ac)

**Comment by HunterDNiu** [comment] 2024-08-25 09:41
Dup #3684

**Comment by Luigi-II** [comment] 2024-08-25 11:17
Don't think it could detect target at 1500nm. This is what a 1500nm strategic OTH-B Radar looks like:
![image](https://github.com/user-attachments/assets/59fd34ce-3071-4f70-a8bf-4cff7557fd75)
The SIAR seems to be only 1/3 of the above one's size:
![image](https://github.com/user-attachments/assets/9e25cc47-618e-43a8-83d0-c0a26a26affa)
![image](https://github.com/user-attachments/assets/aa4ca6dc-20f4-49ba-8bc5-0a7a57443460)
Personally speaking, 500nm would be reasonable. What does our dear DB manger think?

**Comment by yUsie108** [comment] 2024-08-25 13:06
More about SIAR
https://www.jhuapl.edu/sites/default/files/2022-12/InDepthSubiReefCounterStealthRadar.pdf

**Comment by PygmalionOfCyprus** [comment] 2024-09-20 17:29
Duplicate of #4803

**Closed as not planned by PygmalionOfCyprus** 2024-09-20 17:29 UTC
Labels: addition, DB3K, sensor
