### ISSUE TITLE
PHL16 MLRS Battery (4 Launchers)

### ISSUE THREAD

**Issue by Siegemiester** [PygmalionOfCyprus/cmo-db-requests#4333] opened 2024-02-21 14:37 UTC
### DB Selector

DB3K

### Hypothetical

No

### Name

PHL-16 (PCL-191) Bty

### Facility Type

SSM

### Country

China

### Service

PLAGF

### In Commission

2019

### Number in Service

>50

### Crew

12

### Dispersion Radius (m)

30m-50m

### Sensors

Naked eye only

### Mounts

4x PHL-16 Launchers
Each PHL-16 launcher to have 2 mounts
Each mount to to choose from the list below:

5x BRE2 300mm Unguided HE Rockets - 130km Range
5x BRE3 300mm Guided HE Rockets - 140km Range
4x BRE6 370mm Guided HE Rockets - 220km Range
4x BRE8 370mm Guided HE Rockets - 280km Range
1x FD480 750mm Tactical Ballistic Missile - 480km Range
1x TL7B AShM - 180km Range

### Magazines

Presumably at least 1 full reload of the entire battery with the same selection of munitions that came preloaded

### Comments

Sorely needed for any Taiwan straits scenario
Also china's counterpart to the HIMARS which means it should have comparable reload times

### Sources

https://en.wikipedia.org/wiki/PHL-16

https://www.andrewerickson.com/2023/11/china-maritime-report-32-the-pch191-modular-long-range-rocket-launcher-reshaping-the-pla-armys-role-in-a-cross-strait-campaign/

**Comment by LuigiP57** [comment] 2024-02-21 15:24
duplicate of #1979 #988

**Comment by PygmalionOfCyprus** [comment] 2024-06-17 22:40
Duplicate of #988

**Closed as not planned by PygmalionOfCyprus** 2024-06-17 22:40 UTC
Labels: addition, DB3K, facility
