### ISSUE TITLE
Add Ukrainian TU-141 (Bomb-capable, Mod 2022/2023)

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#2998] opened 2023-02-07 12:44 UTC
### DB Selector

DB3K

### DBID to Copy

Aircraft 2569

### Hypothetical

No

### Name

TU-141 UAV, Ukraine (Bomb-capable, Mod 2022/2023)

### Country

Ukraine

### Service

Air Force

### Sensors

No Change

### Mounts

No Change

### Loadout Options

Same as Aircraft 2569 with addition to:

Bomb loadout
1x OFAB-100-200 bomb

### Other Changes

- Add "Bombsight - Basic" to the aircraft

### Sources

- https://www.seattletimes.com/nation-world/world/investigators-drone-that-crashed-in-croatia-carried-a-bomb/
- https://twitter.com/mdfzeh/status/1622584239148642304
- https://twitter.com/RALee85/status/1622564163124973568
- https://twitter.com/KSOSINT/status/1514287193686224899

**Comment by tbrandon517** [comment] 2023-02-07 14:50
Duplicate of #2882

**Comment by PygmalionOfCyprus** [comment] 2023-05-12 18:29
Duplicate of #2882

**Closed by PygmalionOfCyprus** 2023-05-12 18:29 UTC
Labels: aircraft, DB3K, copy
