### ISSUE TITLE
Spanish Typhoons with Brimstone missiles

### ISSUE THREAD

**Issue by Huib18** [PygmalionOfCyprus/cmo-db-requests#3138] opened 2023-03-05 17:11 UTC
### DB Selector

DB3K

### User(s)

#5507 and #5508

### Weapons Carried

Brimstone missile loadout per 2023. Same as RAF loadout except IRIS-T for ASRAAM missiles.
![Clipboard01](https://user-images.githubusercontent.com/60408110/222975228-b38bd443-a431-4612-b1c2-e39205ae24e3.jpg)

### Requires Buddy Illumination

No

### Default Combat Radius (nm)

Same as RAF configuration

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Comments

Same as RAF configuration

### Sources

[https://www.janes.com/defence-news/weapons-headlines/latest/spain-to-equip-eurofighters-with-brimstone-missile?utm_campaign=Social_News&utm_content=231788653&utm_medium=social&utm_source=twitter&hss_channel=tw-70529694](url)
[https://eurasiantimes.com/eurofighter-typhoons-to-be-armed-with-brimstone-missiles-british/](url)

**Comment by tbrandon517** [comment] 2023-03-05 21:29
Duplicate of #2630

**Comment by PygmalionOfCyprus** [comment] 2023-06-13 18:41
Duplicate of #2630

**Closed by PygmalionOfCyprus** 2023-06-13 18:41 UTC
Labels: DB3K, loadout
