### ISSUE TITLE
Japan ASM-3A 

### ISSUE THREAD

**Issue by Huacangzi** [PygmalionOfCyprus/cmo-db-requests#4742] opened 2024-07-14 16:12 UTC
### DB Selector

DB3K

### Baseline

722

### Hypothetical

No

### Name

ASM-3A

### Length (m)

6

### Width/Span (m)

1

### Diameter (m)

0.4

### Weight (kg)

940

### Range (nm)

2-160

### Target Altitude / Depth (ft)

200-35000

### Target Speed (kts)

1450-2000

### Launch Altitude / Depth (ft)

200-35000

### LaunchSpeed (kts)

270-650

### Warhead

200KG HE

### Targets

Surface Vessel, Land Structure - Soft, Land Structure - Hardened

### CEP (m)

4

### Sensors

Activr Radar Seeker×5nm
IIR Seeker×25/10nm
Passive Radar Seeker×10nm

### Weapon Codes

Uses GPS

### Comments

The range of ASM-3 is 108nm,ASM-3 is test only,not in use.

### Sources

https://ja.wikipedia.org/wiki/ASM-3?wprov=sfla1

**Comment by LuigiP57** [comment] 2024-07-14 16:29
Duplicate of #1940 #3598. If you are new here and want to submit ticket. Please search the keywords of what you want to propose in advance, in order to avoid duplicate. : )

**Closed as not planned** 2024-07-16 19:18 UTC
Labels: addition, DB3K, weapon
