### ISSUE TITLE
Ethiopia, Akinci UCAV

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#4176] opened 2024-01-21 20:54 UTC
### DB Selector

DB3K

### DBID to Copy

Aircraft 4998

### Hypothetical

No

### Name

Bayraktar Akinci UCAV

### Country

Ethiopia

### Service

Air Force

### In Commission

2024

### Sources

[4998](https://twitter.com/HammerOfWar5/status/1747327061130203352)
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/35732829/8b8a9962-7846-4fa6-b5d4-0ec4635effe6)
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/35732829/2158188a-244d-49ad-b9d5-23d6afd5f97e)
https://www.defenceweb.co.za/aerospace/aerospace-aerospace/ethiopia-acquires-akinci-uavs-su-30-fighters/

**Comment by PygmalionOfCyprus** [comment] 2024-01-23 19:47
Duplicate of an issue in our internal news roundup tracker, just closing here so it doesn't get missed. Will be handled 505.

**Closed by PygmalionOfCyprus** 2024-01-23 19:47 UTC
Labels: aircraft, DB3K, copy
