### ISSUE TITLE
Swedish Air Force AIM-120C-8 (D?) loadouts

### ISSUE THREAD

**Issue by og0172peli** [PygmalionOfCyprus/cmo-db-requests#3580] opened 2023-07-11 20:46 UTC
### DB Selector

DB3K

### User(s)

Swedish Air Force

### Weapons Carried

JAS 39C Gripen
2x RB 101 Meteor
2x RB 99B (?) AMRAAM (AIM-120C-8)
2x RB 98 IRIS-T
1x 1275 liter drop tank

JAS 39E Gripen
4x RB 101 Meteor
2x RB 99B (?) AMRAAM (AIM-120C-8)
2x RB 98 IRIS-T
1x 1275 liter drop tank

### Requires Buddy Illumination

No

### Default Combat Radius (nm)

15 minutes at 350 nm CAP

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Comments

Swedish Air Force are to buy 250 AIM-120C-8 missiles from the US. I think that the C-8 is the same missile as AIM-120D but I can be wrong.

There are pictures with JAS 39C carrying both Meteor and AMRAAM missiles. (Se below) So if you could add that loadout mix to C and E variants.

Meteor is RB 107 in the database for Sweden. From what I can figure the designation is RB 101.
The designation for the new missile is unknown, maybe RB 99B or RB 102.

Could you also add the existing loadouts for Swedish JAS C/E with the new AIM-120C-8 missiles instead of Meteors? The Meteor loadouts should also be avaliable as Meteor and the new AMRAAMS will be around for a long time.

 

### Sources

https://www.dsca.mil/press-media/major-arms-sales/sweden-aim-120c-8-advanced-medium-range-air-air-missile-amraam

https://www.goodfon.com/wallpaper/shassi-gripen-jas-39-saab-vvs-shvetsii-gripen-jas-39-ptb-mbd.html

https://sv.wikipedia.org/wiki/MBDA_Meteor

**Comment by KLABDB3K** [comment] 2023-07-11 21:16
https://github.com/PygmalionOfCyprus/cmo-db-requests/issues/3561
Already requested in general, but as stated not sure C8 is not just a refurbished C7?

**Comment by og0172peli** [comment] 2023-07-12 14:15
Sweden received 213 AIM-120A in 1994 and 53 AIM-120C-5 in 2004. If it's refurbished missiles they come from the US. What I know there are no AIM-120C-8. They where redesignated AIM-120D. But maybe there are som informal designation of refurbished C-7's. The range is said to be 160 km in the below article. Maybe that will give you a clue which missile it is.

https://www.turdef.com/article/sweden-buys-250-amraam

**Comment by og0172peli** [comment] 2023-07-12 14:16
And sorry if I posted twice, I cant see the other post in the list, that's why

**Comment by og0172peli** [comment] 2023-07-12 17:50
I've just noticed in the game that when you arm Norwegian F-35A with AIM-120C-8 AMRAAM loadout it says AIM-120D in the loadout details box so according to the database they are the same.

**Comment by PygmalionOfCyprus** [comment] 2023-07-14 16:44
Yeah, C-8 is an alternate term / specific phase build of the AIM-120D, at least according to my sources.

**Comment by PygmalionOfCyprus** [comment] 2023-07-14 16:49
Duplicate of #3575

**Closed by PygmalionOfCyprus** 2023-07-14 16:49 UTC
Labels: DB3K, loadout

**Comment by KLABDB3K** [comment] 2023-07-14 19:44
https://www.rtx.com/news/news-center/2023/04/18/most-advanced-amraam-variant-aim-120d-3-completes-critical-milestone-for-operat
https://www.c4defence.com/en/aim-120c-8-plan/
https://www.thedrive.com/the-war-zone/43483/latest-amraam-air-to-air-missile-aims-to-keep-pace-with-china
https://www.janes.com/defence-news/news-detail/norway-receives-us-department-of-state-approval-for-amraam-order

Janes is of the same opinion C8 is an export D3 but one of the above articles implies a lack of data link. I suspect this is an encryption/EW/ECCM capability difference  and the fact that C8 is going to users such as Pakistan where the intelligence and security relationship can be fluid probably speaks volumes.
