### ISSUE TITLE
F/A-18E/F Super Hornet - A/A: AIM-120D AMRAAM, Maximum

### ISSUE THREAD

**Issue by KJohnston11** [PygmalionOfCyprus/cmo-db-requests#3181] opened 2023-03-13 02:58 UTC
### DB Selector

DB3K

### User(s)

All AMRAAM-capable F/A-18s (F/A-18C/D/E/F)

### Weapons Carried

- 10x AIM-120D AMRAAM
- 2x AIM-9X Sidewinder
- 1x AN/ASQ-228 Terminator II ATFLIR [FLIR + LRMTS, 40k ft]
- 1x 330 USG Centerline Drop Tank

### Requires Buddy Illumination

No

### Default Combat Radius (nm)

495 nm

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Sources

https://commons.wikimedia.org/wiki/File:FA-18_Hornet_VX-4_with_10_AMRAAM.jpg

**Comment by tbrandon517** [comment] 2023-03-13 09:21
Duplicate of #290

**Comment by FrangibleCover** [comment] 2023-03-15 10:34
Not a exactly a duplicate of 290, but more than one request:
- 1. Max AMRAAM loadouts for Legacy Hornets (10x, as depicted in the linked picture)
- 2. Max AMRAAM loadouts for Super Hornets (so far unknown)
- 3. Max AMRAAM loadouts for Super Hornet Block IIIs (12x, duplicate of 290)

The image depicting ten AMRAAMs on an F/A-18C is from a trials unit, so I'm not sure if it was flown operationally by the USN, but there are multiple images/videos of the Swiss Air Force running the loadout on both a C and a D. I can't see any reason to run the trial the US has already run, never mind to do so on two different airframes, so I assume this is an operational loadout for them? I would therefore imagine that every operator uses it, or at least every operator with the dual racks needed.

**Comment by KJohnston11** [comment] 2023-03-15 21:21
realized duplicate

**Closed** 2023-03-15 21:20 UTC
Labels: DB3K, loadout
