### ISSUE TITLE
Japan’s Type 12 SSM (Upgraded)

### ISSUE THREAD

**Issue by Goshawk-1** [PygmalionOfCyprus/cmo-db-requests#3261] opened 2023-04-07 09:07 UTC
### DB Selector

DB3K

### Baseline

SSM-2 [Type 17]

### Hypothetical

No

### Name

 Type 12 SSM (Upgraded)

### Length (m)

5

### Width/Span (m)

?

### Diameter (m)

350

### Weight (kg)

700

### Range (nm)

486

### Warhead

HE

### Targets

Surface Vessel, Land Structure - Soft, Land Structure - Hardened

### Sensors

Up to Date Command (UDTC), which allows the missile to receive information about the target via satellite communications while in flight

### Sources

Here Is Our First Look At Japan’s Type 12 SSM (Upgraded)
[https://www.navalnews.com/naval-news/2022/08/here-is-our-first-look-at-japans-type-12-ssm-upgraded/](url)

DSEI Japan 2023: Japan expects to induct upgraded Type 12 SSM by 2026
[https://www.janes.com/defence-news/news-detail/dsei-japan-2023-japan-expects-to-induct-upgraded-type-12-ssm-by-2026#:~:text=Features%20of%20the%20upgraded%20Type,receive%20in%2Dflight%20target%20updates.](url)

**Comment by PygmalionOfCyprus** [comment] 2023-05-31 18:28
Duplicate of #3231

**Closed by PygmalionOfCyprus** 2023-05-31 18:28 UTC
Labels: addition, DB3K, weapon
