### ISSUE TITLE
PA-1 Panoramic Camera

### ISSUE THREAD

**Issue by Udakhin** [PygmalionOfCyprus/cmo-db-requests#2838] opened 2023-01-13 18:54 UTC
### DB Selector

Both

### Hypothetical

No

### Name

PA-1 Panoramic Camera

### Sensor Generation

Late 1970s

### Range (nm)

5.0

### Sensor Capabilities

Surface Search, Land Search - Fixed Facility, Land Search - Mobile Unit, Heading Information

### Sensor Codes

Identification Friend or Foe (IFF) [Side Info], Classification [Class Info] / Brilliant Weapon [Automatic Target Acquisition]

### Comments

VisualDetectionZoomLevel = 4.0
VisualClassificationZoomLevel = 4.0

### Sources

https://www.armedconflicts.com/topic/view/45670/SOV-KKR-1-KKR-2

http://www.manfred-bischoff.de/SU22.htm#Aufkl%C3%A4rungsbeh%C3%A4lter%20KKR-1T

V.Markovsky, I.Prikhodchenko, “Su-17 in Action”, Moscow, 2016 (В.Марковский, И.Приходченко. «Су-17 в бою». Москва, 2016)

**Comment by PygmalionOfCyprus** [comment] 2023-01-13 18:58
Duplicate of #2794

**Closed by PygmalionOfCyprus** 2023-01-13 18:58 UTC
Labels: addition, CWDB, DB3K, sensor
