### ISSUE TITLE
South Korea, Type 214, correction

### ISSUE THREAD

**Issue by KC45jp** [PygmalionOfCyprus/cmo-db-requests#1584] opened 2022-07-03 21:31 UTC
### DB Selector

DB3K

### Affected DBID(s)

Submarine ID 420, 669, 670

### Summary of Changes

Minor weirdness, not critical
South Korean Type 214 have 2x and 6x torpedo launchers. I do not know why, but while other Type 214 class have 8x torpedo launchers, I believe this is a bug.

Bug became bit critical for 2020 version (ID 670). This class can load Harpoon, White Shark, and Tiger Shark for any torpedo launcher, not only 2 tube can shoot white shark nor other 6 can shoot Tiger Shark. Type 214 Magazine should able to hold all three types of weapon.

### Sources

None

**Comment by PygmalionOfCyprus** [comment] 2022-07-05 04:24
Duplicate of #1591

**Closed by PygmalionOfCyprus** 2022-07-05 04:24 UTC
Labels: DB3K, submarine, update
