### ISSUE TITLE
C-146A Wolfhound

### ISSUE THREAD

**Issue by trevor99999** [PygmalionOfCyprus/cmo-db-requests#4547] opened 2024-05-22 02:18 UTC
### DB Selector

DB3K

### Baseline

Dornier 328

### Hypothetical

No

### Name

C-146A Wolfhound

### Country

United States

### Service

USAF

### In Commission

2011-present

### Number in Service

20x

### Length (m)

21.29

### Wingspan (m)

20.98

### Height (m)

7.24

### Empty Weight (kg)

8920kg (Do328)

### Maximum Takeoff Weight (MTOW) (kg)

13990

### Crew

2 or 3

### Propulsion

2x Pratt & Whitney PW119C turboprop engines

### Service Ceiling (ft)

9492

### Military/Afterburner Speed (kt)

330kts (?)

### Cruise Speed (kt)

270 kt (?)

### Supercruise

No

### Ferry Range (nm)

unknown max range 1500nm w/ 2000lb payload

### Fuel Capacity (kg)

4268 litres

### Sensors

Honeywell Primus 2000 

### Mounts

none

### Loadout Options

passengers, VIP(?), Special Forces, litter patients

### Comments

Intra-theater mobility for special operations forces
Maximum of 27 passengers, 6,000 pounds of cargo, or up to four litter patients.
Able to use prepared and semi-prepared airfields

### Sources

https://www.af.mil/About-Us/Fact-Sheets/Display/Article/467729/c-146a-wolfhound/
https://theaviationist.com/2022/05/13/u-s-c-146a-landing-latvia/
https://en.wikipedia.org/wiki/Dornier_328

**Comment by tbrandon517** [comment] 2024-05-22 09:53
Duplicate of #3098

**Closed as not planned** 2024-05-22 16:51 UTC
Labels: addition, aircraft, DB3K
