### ISSUE TITLE
Load out SU-30SM2 R-37M Axehead/Arrow 

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#4555] opened 2024-05-23 08:44 UTC
### DB Selector

DB3K

### User(s)

Russia VKS/Navy(?) 

### Weapons Carried

3* x R-37M AA-13 Arrow / Axehead
2 x R-77-1 AA-12B Adder
2* x R-73M AA-11 Archer

2* x Wing tip ECM pods 

Would seem easier to copy Su-35 loadout?
*Not seen with R-73 but highly likely and no reason it wouldn't be.
*probable ECM given threat level. 
*Fourth R-37M in engine tunnel?? 

NB Also they still lack the Kh-31PM AS-17 Krypton E ARM load outs. The upgraded Krypton ARM has been the default production model since 2012.

### Requires Buddy Illumination

No

### Default Combat Radius (nm)

As extant AA radius

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Comments

Possibly a fourth R-37M between the engine but it's not visible in the images. ECM pods and R-73 are likely for an operational load as are the mixed AAW/SEAD loads seen on other SU-30/35? 

### Sources

X Twitter
https://x.com/GuyPlopsky/status/1793242596875329683?t=MCd9LCjNvOvM06WqVIERlA&s=19
https://x.com/MrFrantarelli/status/1793310939632013819?t=G7UOM1iVXrxAg9q2Xs7yoQ&s=19 from April. This image is of Russian Navy SU-30SM2.

**Comment by LuigiP57** [comment] 2024-05-23 10:31
duplicate of #4552

**Comment by sr71xx** [comment] 2024-05-23 11:01
it's been recently added

**Closed as completed** 2024-05-24 06:38 UTC
Labels: DB3K, loadout
