### ISSUE TITLE
Add IAIO Qaher-313 (UCAV version)

### ISSUE THREAD

**Issue by capcop98** [PygmalionOfCyprus/cmo-db-requests#3474] opened 2023-06-14 11:30 UTC
### DB Selector

DB3K

### Baseline

Aircraft 1905

### Hypothetical

Yes

### Name

IAIO Qaher-313 (UCAV variant)

### Country

Iran

### Service

Air Force

### Number in Service

1x (prototype)

### Length (m)

15.5

### Wingspan (m)

8.0

### Height (m)

4.08

### Empty Weight (kg)

4400

### Maximum Takeoff Weight (MTOW) (kg)

9000

### Crew

0

### Propulsion

2x J-90 OWJ

### Rate of Climb (ft/min)

25000

### Service Ceiling (ft)

49213

### Military/Afterburner Speed (kt)

810 kt

### Cruise Speed (kt)

480

### Supercruise

No

### Ferry Range (nm)

1080

### Sensors

(Hypothetical)
1x IEI BAYYENAT I(Sensor/6997)

IEI SAIRAN Electronic Warfare suite that included:
1x RWR(Sensor/2919)
1x MAWS(Sensor/2216)
1x ECM Jammer (Sensor/825)

With addition to:
1x Generic IR camera
1x Generic laser designator
![image](https://user-images.githubusercontent.com/99646926/208232703-7891f047-62c8-4f97-a46f-dfcc8d1e5fac.png)

### Mounts

1x Generic chaff/flare dispenser

### Loadout Options

Air-to-Air
The aircraft were claimed to be able to carry up to 6x missiles like PL-12. So the loadout is probably
![image](https://user-images.githubusercontent.com/99646926/208232380-c965c9cd-1cf3-4ac0-8472-6168e94f0587.png)

4x PL-12(Weapon 1116) and 2x Fatter AAM(Weapon 4159)
or
4x R-77(Weapon 273) and 2x Fatter AAM(Weapon 4159)
or
R-27R(Weapon 1901) and 2x Fatter AAM(Weapon 4159)
or
2x Fakour-90(Weapon 2784) and 2x Fatter AAM(Weapon 4159)

Air-to Ground
And the aircraft were also claimed to be able to carry maximum of up to 2x 2000lb bombs and many more for smaller guided bombs.
![image](https://user-images.githubusercontent.com/99646926/208232363-36dd8a87-d8c7-4863-9038-d2b98edcb2bb.png)
Hypothetically speaking, it probably can carry:

2x Qassed-1 and Qassed-3(Copy of AGM-130, 100km range + INS/GPS midcourse instead of datalink) with 2x Fatter AAM
and
4x Yasin guided bomb(Weapon 4120) with 2x Fatter AAM(Weapon 4159)
and
4x Sattar-4 guided bomb (Weapon 3088) with 2x Fatter AAM(Weapon 4159)
and
8x Balaban SDB (Weapon 3647) with 2x Fatter AAM(Weapon 4159)

It were claimed to have Internal weapon bays, so RCS will probably remain the same for all loadouts.
![image](https://user-images.githubusercontent.com/99646926/208232262-fdf855a8-f75a-4c1f-965d-0e2ca6476816.png)
![image](https://user-images.githubusercontent.com/99646926/208232286-9882e539-2d0e-4420-aeff-aa849fc45372.png)

### Comms/Datalinks

Generic Military SATCOM
UHF Radio [Secure]
VHF Radio [Secure]
AA-10/12 Datalink

### Aircraft Codes

Night Navigation/Attack (Incl. Bomb, Rocket Delivery), Bombsight - Advanced Computing

### Sources

- https://www.aerotime.aero/articles/iran-to-build-unmanned-version-of-qaher-313-fighter-jet-official-says
- https://eurasiantimes.com/iran-to-convert-its-f-35-replica-fifth-gen-stealth-fighter/
- https://www.tasnimnews.com/en/news/2023/02/19/2855329/iranian-fighter-jet-to-become-unmanned-aircraft
- #2688

**Comment by zulualpha91** [comment] 2023-07-19 00:30
More pics (3d model and photoshop) of the UCAV variant for references
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/122736922/5497c86a-699e-47b1-8154-0b62dfd6cde5)
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/122736922/16289ba0-5460-4bd6-a0d7-15509959a3b1)

**Comment by capcop98** [comment] 2023-07-19 00:32
More pics (3d model and photoshop) of the UCAV variant for references
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/122736922/5497c86a-699e-47b1-8154-0b62dfd6cde5)
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/122736922/16289ba0-5460-4bd6-a0d7-15509959a3b1)

Source: https://twitter.com/AryJeay/status/1627268535184420864/photo/2

**Comment by PygmalionOfCyprus** [comment] 2024-10-11 18:53
Closing as duplicate of #2688, I know this is for the UCAV version but I can just work with the one ticket.

**Closed by PygmalionOfCyprus** 2024-10-11 18:53 UTC
Labels: addition, aircraft, DB3K, hypo
