### ISSUE TITLE
Add Egyptian 804 Al Aziz [Meko-A200EN] x 4 2023

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#932] opened 2022-04-19 17:22 UTC
### DB Selector

DB3K

### DBID to Copy

3020

### Hypothetical

No

### Name

804 Al Aziz [Meko-A200EN]

### Country

Egypt

### Service

Navy

### In Commission

2023

### Sensors

Thales NS-110 4D AESA radar
Thales SCORPION 2 ECM
ALTESSE-H CESM & COMINT, 
Mirador Mk2 EO/IR
Hull Sonar Thales UMS4132 Kingklip HMS
towed unknown but Captas likely
Nav Radars visible but not sure on type. (nav radar is a nav radar). I'd add Scout to start.

### Mounts

Leonardo LW 127mm vulcano main gun,
32× VLS for MICA-NG SAM, 
8× MM40 Block3 Exocet SSM (2 quads)
4× MASS, 
2× WASS, 
4× 20mm Sea Ranger guns,
2 Triple torpedo launchers 
MU-90 Torpedoes

### Other Changes

Should have facilities to support 1 NH-90.
2 RHIB Davits

### Sources

https://www.navyrecognition.com/index.php/naval-news/naval-news-archive/2022/april/11599-egyptian-navy-s-meko-a200-frigate-el-aziz-starts-sea-trials.html
https://twitter.com/mahmouedgamal44/status/1511308502635003904
https://www.navyrecognition.com/index.php/naval-news/naval-news-archive/2020/september/8999-mbda-to-supply-vl-mica-surface-to-air-missiles-for-meko-a-200-frigates-of-egyptian-navy.html
https://www.janes.com/defence-news/news-detail/searanger-naval-guns-ordered-for-egypt
https://twitter.com/D__Mitch/status/1446392123515867139
https://navalpost.com/egypt-begins-local-manufacturing-of-meko-a200-frigate/
https://en.wikipedia.org/wiki/MEKO_200
https://www.savetheroyalnavy.org/wp-content/uploads/2019/03/A200-Arrowhead-v-Leander-comparison-1.pdf
Sipri Lines
4	VL-MICA-M	naval SAM system	2021			For MEKO-200 frigates; VL-MICA NG version
4	LM-2500	gas turbine	(2019)			For 4 MEKO-A200 frigates from Germany

**Comment by PygmalionOfCyprus** [comment] 2022-04-20 00:56
Duplicate of #812

**Closed by PygmalionOfCyprus** 2022-04-20 00:56 UTC
Labels: duplicate, DB3K, ship, copy
