### ISSUE TITLE
Add AN/ALQ-212 ATIRCM to US CH-47F

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#2402] opened 2022-10-11 22:43 UTC
### DB Selector

DB3K

### Affected DBID(s)

2890

### Summary of Changes

Less than 100 fitted so not all CH-47F have this system. IOC before CH-47F so at introduction.

Add AN/ALQ-212 ATIRCM #70 to US CH-47F. This will eventually be replaced by CIRCM #6412

### Sources

If you look at picture its below the back window. Avationist points it out in a caption. Looks likes cylinder where as CIRCM is rounder.
https://theaviationist.com/2021/05/06/northrop-grumman-circm/
https://www.deagel.com/Protection%20Systems/ANALQ-212%20ATIRCM/a001679
https://www.thedrive.com/the-war-zone/31712/night-stalker-chinook-special-operations-helicopters-have-new-laser-countermeasures-system
https://www.thedrive.com/the-war-zone/29240/army-black-hawks-are-finally-getting-laser-countermeasures-to-throw-off-infrared-missiles

**Comment by PygmalionOfCyprus** [comment] 2022-10-12 14:58
Duplicate of #2385

**Closed by PygmalionOfCyprus** 2022-10-12 14:58 UTC
Labels: aircraft, DB3K, update
