### ISSUE TITLE
Addition: DF-27

### ISSUE THREAD

**Issue by HunterDNiu** [PygmalionOfCyprus/cmo-db-requests#3335] opened 2023-04-25 11:26 UTC
### DB Selector

DB3K

### Baseline

2879, 2880, 2881

### Hypothetical

Yes

### Name

DF-27

### Length (m)

14

### Width/Span (m)

1.4

### Diameter (m)

1.4

### Weight (kg)

20000

### Range (nm)

3000

### Warhead

Nuclear(200kts)/HE/Penetrator/ASBM(Penetrator)/Submunitions

### Targets

Surface Vessel, Land Structure - Soft, Land Structure - Hardened, Runway, Mobile Target - Soft, Mobile Target - Hardened, Mobile Target - Personnel

### CEP (m)

10

### Sensors

For the Anti-Ship variant:
Active radar seeker, 80nm, 
Passive radar seeker, 200nm, 
IR seeker. 

### Weapon Codes

Home On Jam (HOJ), Bearing-Only Launch (BOL), Ballistic Missile or Rocket Booster, Weapon - INS Navigation, Level Cruise Flight

### Comments

DF-26 Booster with HGV. 
Terminal speed ~Mach 10. 

### Sources

https://thebulletin.org/about-us/annual-report/?utm_source=Website&utm_medium=Banner&utm_campaign=FullSiteBanner&utm_content=Bulletin_AnnualReport
https://eurasiantimes.com/china-tested-new-df-27-hypersonic-icbm-that-can-penetrate/
https://www.washingtonpost.com/world/2023/04/10/pentagon-document-leak-russia-china-israel/
https://en.wikipedia.org/wiki/Dongfeng_(missile)#Dongfeng_27

**Comment by LuigiP57** [comment] 2023-04-25 14:05
Duplicate of #3135

**Comment by PygmalionOfCyprus** [comment] 2023-06-13 18:40
Duplicate of #3135

**Closed by PygmalionOfCyprus** 2023-06-13 18:40 UTC
Labels: addition, DB3K, weapon, hypo
