### ISSUE TITLE
[HIPRI] China, FC-31 (J-35) radar adjustment

### ISSUE THREAD

**Issue by yUsie108** [PygmalionOfCyprus/cmo-db-requests#4905] opened 2024-08-18 16:08 UTC
### DB Selector

DB3K

### DBID to Copy

Sensor 4865

### Hypothetical

No

### Name

China FC-31 Radar (14XX)

### Country

China

### Service

PLANAF，PLAAF(?)

### In Commission

2023-

### Number in Service

5+

### Other Changes

I brought up this issue mainly because in beta I encountered the FC-31 radar being combined with the F-17C Thunder Blk 3 radar.
As a fifth-generation fighter to be developed in the 2020s, its radar should not only be at its current level.
I found your discarded radar originally used for FC-31 and its DBID, hoping to rename it and re-match it for use with FC-31. Meanwhile, I hope you will not forget the issue I submitted before, add LPI and SAR characteristics to this radar simultaneously, and modify the radar of this radar to the early 2020s. I trust this work will not take up too much of your time;)
At the end, due to the problem of my account unfortunately, in order to submit this update, I have to create a new account to submit the ticket

### Sources

DB itself.
![image](https://github.com/user-attachments/assets/5edaa027-0bcd-4d2a-b062-908f8841e3aa)

**Comment by PygmalionOfCyprus** [comment] 2024-08-22 22:30
At least during early development there was speculation that the FC-31 might in fact be using the KLJ-7A radar. The aircraft was originally intended for export, after all; certainly back in 2012ish I think it would be fair to assume the radar was onboard.  https://web.archive.org/web/20161229165941/http://www.janes.com/article/65359/new-details-emerge-on-shenyang-fc-31-fifth-generation-export-fighter

This is still reported in many sources, although I suspect that's just because it's what's on the EN Wikipedia page...nevertheless, the hum about the FC-31 and the KLJ-7A continues to pop up, enough to make me think it's more than just coincidence, e.g.: https://www.sinodefenceforum.com/t/shenyang-fc-31-j-31-fighter-demonstrator.5693/post-619128

It is wholly possible -- perhaps even likely -- that in eventual PLA service (if indeed this ever occurs) it would be replaced with a more powerful, stealthier radar. If this happened it would have been back in ~22 or so, when the program was reorganized from an export program to one following PLAN/PLAAF specifications. 

But until we receive proof of such, I'm hesitant to replace it with a generic. I think we should assume that it still has this radar for now. Besides, as a more low-end alternative to the J-20, using a variant of the KLJ-7A isn't outside the realm of possibility, though I admit the lack of any stated LPI capability is...suboptimal for a "stealth" fighter.

Note that for this latter reason and based on confirmed info I am not going to give the KJL-7A LPI characteristics. I have however modified the era of the KLJ-7A to Early 2010s as it was released in 2016.

**Closed as not planned** 2024-08-22 22:41 UTC
Labels: DB3K, sensor, copy
