### ISSUE TITLE
Korea Airforce F-16PBU

### ISSUE THREAD

**Issue by clerara10** [PygmalionOfCyprus/cmo-db-requests#3006] opened 2023-02-11 00:23 UTC
### DB Selector

DB3K

### DBID to Copy

Aircraft 160

### Hypothetical

No

### Name

F-16 PBU

### Country

Republic of Korea

### Service

ROKAF

### In Commission

2016-

### Number in Service

34

### Sensors

1x AN/APG-68(V)7
ALQ-88/200K
LANTIRN
AN/AAQ-28 (v)4
### Mounts

20mm M61A1x1

### Loadout Options

AIM-120C
AIM-9X
JDAM
AGM-88
AGM-84
GBU-39
KGGB
SPICE 2000

### Other Changes

Link 16
AN/ARC-238

F-16PBU is upgrade from F-16 PB in 2016

### Sources

https://www.airforce-technology.com/news/us-to-upgrade-f-16-block-32-aircraft-and-equipment-for-korea/

https://www.dsca.mil/press-media/major-arms-sales/republic-korea-f-16-block-32-aircraft-upgrades

https://www.ainonline.com/aviation-news/defense/2017-11-07/korean-f-16s-upgraded-carry-israeli-weapon

https://www.airliners.net/photo/South-Korea-Air-Force/General-Dynamics-F-16PBU-Fighting-Falcon/5723701/L

**Comment by FrangibleCover** [comment] 2023-02-11 14:36
Duplicate of #1522

**Closed** 2023-05-12 18:12 UTC
Labels: aircraft, DB3K, copy
