### ISSUE TITLE
AGM-88 HARM on Ukrainian MiG-29 Fucrums

### ISSUE THREAD

**Issue by Huib18** [PygmalionOfCyprus/cmo-db-requests#2057] opened 2022-08-20 19:04 UTC
### DB Selector

DB3K

### User(s)

#1402 and #2613

### Weapons Carried

AGM-88B DB# 650

### Requires Buddy Illumination

No

### Default Combat Radius (nm)

Same as now with the AA-10 Alamo loadout

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Comments

Maybe a hypothetical option for the #2840 MiG-29 Fulcrum A Poland 2014, MLU

Exactly what AGM-88 variants the U.S. military has provided to the Ukrainians, how the integration of those missiles onto the MiG-29 was specifically achieved, and what modes the weapons can be employed in from those aircraft all remain unclear.
Lets choose AGM-88B? DB# 650, or DB#649 AGM-88C? Maybe the US does not wat to give away too much technology?

### Sources

https://www.thedrive.com/the-war-zone/ukrainian-mig-29s-are-firing-agm-88-anti-radiation-missiles
https://twitter.com/yorukhunnn/status/1560896855176781824
https://twitter.com/Taurevanime/status/1557815233091100673
https://www.thedrive.com/the-war-zone/how-ukraine-couldve-quickly-put-agm-88-anti-radiation-missiles-to-use

**Comment by Huib18** [comment] 2022-08-20 19:13
BTW The Slovak airforce also flies with 9x MiG-29AS and 2x MiG-29UBS and are not present in de the DB.

**Comment by KC45jp** [comment] 2022-08-20 20:28
duplicate of #2025

**Comment by tbrandon517** [comment] 2022-08-20 22:25
Related to request #2025

**Comment by KLABDB3K** [comment] 2022-08-25 20:22
https://twitter.com/UAWeapons/status/1562889397980512257?t=ZE8Pf8R5tQ_XAyyKINiBUQ&s=19
AGM-88B with a caveat?

**Comment by Coiler12** [comment] 2022-08-30 09:45
https://twitter.com/UAWeapons/status/1564539358451044353

Would have 2x HARM in place of the Alamos.

**Comment by PygmalionOfCyprus** [comment] 2022-09-02 19:08
Duplicate of #2025

**Comment by PygmalionOfCyprus** [comment] 2023-07-14 21:41
Handled 502. AGM-88 entries were already on the aircraft but needed their own entries.

**Closed by PygmalionOfCyprus** 2023-07-14 21:41 UTC
Labels: DB3K, loadout
