### ISSUE TITLE
Add S-500 Prometheus

### ISSUE THREAD

**Issue by BartGauvin** [PygmalionOfCyprus/cmo-db-requests#208] opened 2022-02-17 17:31 UTC
### DB Selector

DB3K

### Hypothetical

No

### Name

SAM Bn (SA-? [S-500 Prometheus]) -- Russia [1992-], 2021, 12x TEL

### Facility Type

SAM

### Country

Russia

### Service

Air Force

### In Commission

2121

### Crew

?

### Dispersion Radius (m)

80

### Sensors

1x 91N6E(M) S-band acquisition radar, 
1x 96L6-TsP C-band acquisition radar, 
1x 76T6 multi-mode engagement radar, 
1x 77T6 anti-ballistic missile engagement radar

https://missilethreat.csis.org/defsys/s-500-prometheus/
Joseph Trevithick, “Russia’s S-500 Air Defense System Reportedly Hits Target Nearly 300 Miles Away,” The Drive, May 24, 2018, https://www.thedrive.com/the-war-zone/21080/russias-s-500-air-defense-system-reportedly-hits-target-nearly-300-miles-away.

### Mounts

12x S-500 TEL (4x msls per TEL)

40N6M range 400 km (ABM); 
77N6 range 500-600 km

Roger McDermott, “Moscow Weighs Options to Procure S-500 Air-Defense Systems,” Jamestown Foundation, March 24, 2021, https://jamestown.org/program/moscow-weighs-options-to-procure-s-500-air-defense-systems/.

### Magazines

? Probably 1 reload vehicle per TEL as in the other X00 series so 48 but that is speculation

### Aircraft & Docking Facilities

none

### Comments

Planned for 10x Bns by 2025 with the first Bn operational in the Moscow AD ring in Oct 2021

Export options to China, India and Turkey 

### Sources

Missile Defense Project, "S-500 Prometheus," Missile Threat, Center for Strategic and International Studies, May 4, 2017, last modified July 1, 2021, https://missilethreat.csis.org/defsys/s-500-prometheus/.

https://www.thedrive.com/the-war-zone/41627/this-is-our-first-view-of-russias-new-s-500-air-defense-system-in-action

http://www.military-today.com/missiles/s500.htm

https://www.armyrecognition.com/russia_russian_missile_system_vehicle_uk/s-500_prometheus_55r6m_triumfator-m_air_defense_missile_data_pictures_video.html

https://www.wionews.com/world/explainer-how-is-russias-s-500-missile-defence-system-superior-to-s-400-436847

**Comment by PygmalionOfCyprus** [comment] 2022-02-28 03:52
Technically came first but #315 has a bit more info in the ticket so will treat that as the "parent" for ease of entry.

**Comment by PygmalionOfCyprus** [comment] 2022-02-28 03:52
Duplicate of #315

**Closed by PygmalionOfCyprus** 2022-02-28 03:52 UTC
Labels: duplicate, addition, DB3K, facility
