### ISSUE TITLE
Update Canadian CSC (Type-26 frigate)

### ISSUE THREAD

**Issue by Seaside232** [PygmalionOfCyprus/cmo-db-requests#666] opened 2022-03-13 13:12 UTC
### DB Selector

DB3K

### Affected DBID(s)

Latest DB 3000

### Summary of Changes

Update Canadian Type-26 Frigate

### Sources

https://www.navalnews.com/naval-news/2020/11/royal-canadian-navy-unveils-new-details-on-csc-frigates/

**Comment by tbrandon517** [comment] 2022-03-13 13:59
Link to #252

**Comment by Seaside232** [comment] 2022-03-13 14:14
Ok , Thanks . I searched for this . Guess not enough :)
Glad it's being looked at.

**Comment by PygmalionOfCyprus** [comment] 2022-03-14 07:02
Probably didn't see it because the issue was closed; i.e., we already handled it! Guess the CSC must be popular, eh?

**Comment by PygmalionOfCyprus** [comment] 2022-03-14 07:02
Duplicate of #252

**Closed by PygmalionOfCyprus** 2022-03-14 07:02 UTC
Labels: duplicate, DB3K, ship, update

**Comment by PygmalionOfCyprus** [comment] 2022-06-08 06:53
494 is currently only out on private beta. Do you have access to that or are you on the public beta?

**Comment by Seaside232** [comment] 2022-06-08 10:25
Just the public. I was just wondering as the original thread did not have all the latest info.
I can wait :)

Thanks for the reply.
Mark
