### ISSUE TITLE
Please add MD-530F Cayuse Warrior for Afghanistan - from April 2015 to 2021 (Suitable for other countries)

### ISSUE THREAD

**Issue by KLABDB3K** [PygmalionOfCyprus/cmo-db-requests#247] opened 2022-02-17 21:12 UTC
### DB Selector

DB3K

### Hypothetical

No

### Name

MD-530F Cayuse Warrior

### Country

Afghanistan

### Service

Air Force

### In Commission

April 2015 -(out of service 2021?)

### Length (m)

7.3

### Wingspan (m)

1.9

### Height (m)

3

### Empty Weight (kg)

896

### Maximum Takeoff Weight (MTOW) (kg)

2367

### Payload Weight (kg)

454

### Crew

2

### Propulsion

250-C30/R3 #1

### Rate of Climb (ft/min)

5920 ft/min, 30.1 m/sec 

### Service Ceiling (ft)

15000

### Military/Afterburner Speed (kt)

150

### Cruise Speed (kt)

135

### Supercruise

No

### Ferry Range (nm)

230

### Endurance (min)

140

### Takeoff / Landing Distance (m)

0

### Fuel Capacity (kg)

205.0

### Sensors

1x Mk1 Eyeball
1x Generic Night Vision Goggles
Considerbaly less well equipped than similar exported MD-530's. 

### Mounts

NIL

### Loadout Options

HMP 400 Gun Pods (COPY #29911)
(Strike, Land/Naval) 10x 12.7mm HMP 400 Gun Pod Burst [40 rnds]
 
HYDRA 70mm Rockets 
(Strike, Land/Naval) 14x HYDRA 70mm Rocket

 

### Comms/Datalinks

UHF/VHF Radio [Unsecure]

### Aircraft Codes

Bombsight - Basic

### Comments

The basic MD-530 is already in the DB for many entries including #5407 - MH-6M Little Bird [MD-530F] (Lebanon - 2021) so it could be copied and then remove the sensors and more advanced load outs.
The Afghan version was austere, lacking effective sensors and defensive aides.
The austere MD-530F version has been seen as the helicopter attack platform of choice for US foreign military sales to countries unable to afford to operate the Apache. 
Weapons wise it appears the Afghans operated either with HMP gun pods or 14 Hydra rockets NOT both. 

Out of service date 2021 is speculative given the unknown quantity of whether Taliban can repair and maintain those air frames not rendered totally inoperable. 
Manufacturer data:
Max Gross Weight: Int. 3,300 lb / 1,496 kg
Useful Load 2,159 lb / 979 kg
Service Ceiling 16,000 ft / 4,876 m
Max Cruise Speed 110 kt / 203 kph
HOGE 14,400 ft / 4,389 m
HIGE 16,000 ft / 4,877 m
Range 235 nm / 435 km

### Sources

https://www.airforce-technology.com/projects/md-530f-cayuse-warrior-helicopter/
https://youtu.be/KSrRF65o-MU
https://fnamerica.com/products/fn-airborne-pod-systems/fn-hmp400-pod/
https://youtu.be/py6H_5EyYOo
https://youtu.be/uUvtMSj3908 Shows Hydra 2 x 7 pods. And 1 x HMP400 1 X Hydra
https://www.mdhelicopters.com/afghan-air-force-to-expand-fleet-of-md-530f-cayuse-warrior-helicopters.html Seems only supporting HMP-400 AND Hydra.
https://www.maceaviation.com/case-studies
https://en.wikipedia.org/wiki/McDonnell_Douglas_MD_500_Defender
![image](https://user-images.githubusercontent.com/99494755/154570745-042ce8f2-e5bd-4c46-bc71-c19392cae54d.png)
https://www.reddit.com/r/MilitaryPorn/comments/36qfnm/md_530f_helicopters_of_the_afghan_air_force_armed/

**Comment by tbrandon517** [comment] 2022-02-17 21:18
Duplicate of #165

**Closed** 2022-02-21 06:19 UTC
Labels: duplicate, aircraft, DB3K, copy
