### ISSUE TITLE
 Jordanian Armed Forces,Added SR-5 MLRS

### ISSUE THREAD

**Issue by yU2187sie** [PygmalionOfCyprus/cmo-db-requests#4818] opened 2024-07-25 14:11 UTC
### DB Selector

DB3K

### DBID to Copy

Facility 3623 3126

### Hypothetical

No

### Name

Arty Bty (SR-5 MLRS x 6)

### Country

Jordan

### Service

Jordanian Armed Forces

### In Commission

2021-

### Number in Service

4+

### Sensors

1x Mk1 Eyeball

### Mounts

4x 300mm BRE2 Rocket
0x 300mm BRE2 Rocket
0x 220mm GR1 King Dragon 60 Rocket
0x 220mm GR1 King Dragon 60 Rocket
20x Fire Dragon 122mm Rocket
0x Fire Dragon 122mm Rocket

### Sources

https://x.com/nuwangzi/status/1815976202764521648
![image](https://github.com/user-attachments/assets/fc279fb8-2be2-4e46-b775-b5004c9253b1)

**Comment by PygmalionOfCyprus** [comment] 2024-09-23 19:15
Duplicate of #4974

**Closed as not planned by PygmalionOfCyprus** 2024-09-23 19:15 UTC
Labels: DB3K, facility, copy
