### ISSUE TITLE
Update: DF-41

### ISSUE THREAD

**Issue by HunterDNiu** [PygmalionOfCyprus/cmo-db-requests#3926] opened 2023-10-24 03:58 UTC
### DB Selector

DB3K

### Affected DBID(s)

Facility 3068, 3069, 3187

### Summary of Changes

Change the default weapon to #

### Sources

https://www.tandfonline.com/doi/full/10.1080/00963402.2023.2178713#

**Comment by PygmalionOfCyprus** [comment] 2023-10-25 16:19
Or is this a duplicate of #3926?

**Comment by PygmalionOfCyprus** [comment] 2023-10-27 17:23
Same source, assume same issue, I'm closing as a duplicate unless informed otherwise.

**Comment by PygmalionOfCyprus** [comment] 2023-10-27 17:23
Duplicate of #3925

**Closed by PygmalionOfCyprus** 2023-10-27 17:23 UTC
Labels: DB3K, facility, update, question
