### ISSUE TITLE
add Mi-2 Hoplite

### ISSUE THREAD

**Issue by wolfmanpuck** [PygmalionOfCyprus/cmo-db-requests#3690] opened 2023-08-13 17:17 UTC
### DB Selector

DB3K

### Hypothetical

No

### Name

Mi-2 Hoplite

### Country

North Korea

### Service

1980-current

### In Commission

1980

### Number in Service

48

### Length (m)

11.4

### Wingspan (m)

14.5

### Height (m)

3.75

### Empty Weight (kg)

2,372

### Maximum Takeoff Weight (MTOW) (kg)

3,700

### Payload Weight (kg)

1,328

### Crew

2

### Propulsion

2× PZL GTD-350P turboshaft engines, 300 kW (400 shp) each

### Rate of Climb (ft/min)

890

### Service Ceiling (ft)

13,000

### Military/Afterburner Speed (kt)

110

### Cruise Speed (kt)

108

### Supercruise

No

### Ferry Range (nm)

240

### Sensors

1x Mk1 eyeball

### Mounts

1 x NS-23 23mm Gun
2 x ORO-57K 57mm rocket pods
2 x AT-3 ATGM launchers

### Loadout Options

- 1x NS-23 23mm gun (80 rounds)
OR
- 1x NS-23mm gun (80 rounds)
- 2x  8x57mm S-5 unguided rocket pods (16 rockets total)
OR
- 1x NS-23 23mm gun (80 rounds)
- 2x 2xAT-3 ATGM launchers (4x AT-3 total)

### Comms/Datalinks

UHF/VHF radio

### Comments

Not at this time

### Sources

Number in service: https://www.flightglobal.com/download?ac=90688
Years of service and production, some info on weapons & ability to carry troops: https://www.cia.gov/readingroom/docs/CIA-RDP04T00447R000200810001-3.pdf
Video of NK Mi-2 firing ATGM: https://alert5.com/2016/06/03/north-korean-video-shows-mi-2-firing-atgm/
Performance data: https://en.wikipedia.org/wiki/Mil_Mi-2#Variants
Additional performence and weapon loadou data: https://odin.tradoc.army.mil/Search/WEG/Mi-2

**Comment by FrangibleCover** [comment] 2023-08-14 06:32
Partial duplicate of #380

**Comment by PygmalionOfCyprus** [comment] 2023-08-25 19:12
Duplicate of #380

**Closed by PygmalionOfCyprus** 2023-08-25 19:12 UTC
Labels: addition, aircraft, DB3K
