### ISSUE TITLE
Type 055 HHQ-9B SAMS can't fire due to datalinks

### ISSUE THREAD

**Issue by bostonmyk** [PygmalionOfCyprus/cmo-db-requests#4201] opened 2024-01-25 17:16 UTC
### DB Selector

DB3K

### Affected DBID(s)

Type 055s

### Summary of Changes

Datalinks missing on ship.
[Type 055 Tests.zip](https://github.com/PygmalionOfCyprus/cmo-db-requests/files/14055916/Type.055.Tests.zip)

### Sources

Testing

**Comment by PygmalionOfCyprus** [comment] 2024-01-25 21:12
Duplicate of #4172

**Closed by PygmalionOfCyprus** 2024-01-25 21:12 UTC
Labels: DB3K, update

**Comment by bostonmyk** [comment] 2024-01-25 22:01
Excuuuuuuse me. Had a few so I tested today. My mistake.
