### ISSUE TITLE
Fix: GLSDB

### ISSUE THREAD

**Issue by HunterDNiu** [PygmalionOfCyprus/cmo-db-requests#3217] opened 2023-03-22 10:33 UTC
### DB Selector

DB3K

### Affected DBID(s)

Weapon 4248

### Summary of Changes

#2617

### Sources

https://github.com/PygmalionOfCyprus/cmo-db-requests/issues/2617

**Comment by PygmalionOfCyprus** [comment] 2023-04-07 17:43
Duplicate of #2617

**Closed by PygmalionOfCyprus** 2023-04-07 17:43 UTC
Labels: DB3K, update, weapon
