### ISSUE TITLE
Ethiopia, Su-30

### ISSUE THREAD

**Issue by claudejdev** [PygmalionOfCyprus/cmo-db-requests#4177] opened 2024-01-21 21:24 UTC
### DB Selector

DB3K

### DBID to Copy

Aircraft 4464 Su-30MK Flanker G (Angola 2016)

### Hypothetical

No

### Name

Su-30MK Flanker G

### Country

Ehtiopia

### Service

Air Force

### In Commission

2024

### Number in Service

2+4

### Sources

https://twitter.com/StefanKnippsch3
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/35732829/fe5ff4fb-ce98-482a-aa86-7f29c082cc90)
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/35732829/581866c0-19da-4cb6-9452-cbef3b0d1b9b)

https://www.defenceweb.co.za/aerospace/aerospace-aerospace/ethiopia-acquires-akinci-uavs-su-30-fighters/

> In 2011, the 18 Su-30Ks were transported to the 558th aircraft repair plant in Baranovichi, Belarus, where they were stored for the purpose of further resale. In 2013, Angola acquired 12 of these, with delivery from 2017 to 2019. These were upgraded to Su-30SM standard, giving them the ability to fire anti-ship and air-to-air missiles.*
> 
> It appears Ethiopia has acquired the six remaining Su-30Ks, with deliveries of the last four still to come.

*  Indeed, SIPRI trade register mentions that "2017-2019	12	Second-hand (originally delivered to India but returned to Russian producer) but modernized in Belarus to _Su-30SM_ before delivery; financed with Russian loan"
[Trade-Register-2013-2022.pdf](https://github.com/PygmalionOfCyprus/cmo-db-requests/files/14002859/Trade-Register-2013-2022.pdf)

No ASM mentioned though. Kh29? Kh-58? Your call

**Comment by PygmalionOfCyprus** [comment] 2024-01-23 19:47
Duplicate of an issue in our internal news roundup tracker, just closing here so it doesn't get missed. Will be handled 505.

**Closed by PygmalionOfCyprus** 2024-01-23 19:47 UTC
Labels: aircraft, DB3K, copy
