### ISSUE TITLE
ROKAF F-16PBU

### ISSUE THREAD

**Issue by tksfpj** [PygmalionOfCyprus/cmo-db-requests#2695] opened 2022-12-19 10:43 UTC
### DB Selector

DB3K

### DBID to Copy

Aircraft ID 160

### Hypothetical

No

### Name

F-16 PBU

### Country

Republic of Korea

### Service

ROKAF

### In Commission

2016-

### Sensors

1x AN/APG-68(V)7 (upgrade from APG-68)

### Loadout Options

AIM-120C, AIM-9X, JDAMs, AGM-84, AGM-88, GBU-53

can use pretty much same loadout of KF-16s(2017) but with AIM-9X instead of AIM-9S...

### Other Changes

Comms
Link 16, AN/ARC-238 Radio

F-16PBU is upgraded version of F-16PB(= F-16C Blk 32 Falcon [Peace Bridge] (Aircraft ID 160)).
I believe Name should be "F-16PBU" and add "F-16C Blk 32 [Peace Bridge]" in comment section.
Same change could happen to F-16PB (AC ID 160).

### Sources

https://www.airliners.net/photo/South-Korea-Air-Force/General-Dynamics-F-16PBU-Fighting-Falcon/5723701/L

https://www.ainonline.com/aviation-news/defense/2017-11-07/korean-f-16s-upgraded-carry-israeli-weapon

https://grandfleet.info/us-related/us-approves-korea-f-16c-d-block32-upgrade/

https://www.defenseindustrydaily.com/raytheons-lot-12-aim-9x-missile-orders-07252/

**Comment by KC45jp** [comment] 2022-12-19 15:36
Duplicate of https://github.com/PygmalionOfCyprus/cmo-db-requests/issues/1522

**Comment by FrangibleCover** [comment] 2022-12-19 20:51
Yes, and a very odd duplicate. Almost exactly the same text with minor style adjustments. The account is brand new and has two posts, both in this repository, both clones of a previous request. I'd accuse it of being a bot, but a bot wouldn't make the slight changes.

@tksfpj what's going on, mate?

**Comment by tksfpj** [comment] 2022-12-20 08:57
> Yes, and a very odd duplicate. Almost exactly the same text with minor style adjustments. The account is brand new and has two posts, both in this repository, both clones of a previous request. I'd accuse it of being a bot, but a bot wouldn't make the slight changes.
> 
> @tksfpj what's going on, mate?

Sorry, It's my first time putting in a request, so I've been referring to it a lot, but it seems to have gone wrong due to a copy error I made some changes to some parts

**Comment by PygmalionOfCyprus** [comment] 2023-06-13 17:47
Duplicate of #1522

**Closed by PygmalionOfCyprus** 2023-06-13 17:47 UTC
Labels: aircraft, DB3K, copy
