### ISSUE TITLE
Yugoslavia - PT201 motor gun/torpedo boats (1943/1944)

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#2262] opened 2022-09-28 17:29 UTC
### DB Selector

DB3K

### DBID to Copy

ship 1423

### Hypothetical

No

### Name

PT201 motor gun/torpedo boats (1943/1944)

### Country

Yugoslavia

### Service

Navy

### In Commission

1943-1956

### Number in Service

8x

### Sensors

SO or SCR-517A radar

### Mounts

1 x 1 - 40mm/56 Mk 1.2, 
2 x 1 - 20mm/70 Mk 4, 
2 x 2 - 12.7mm/90, 
(2 - 3) x 2 - 7.62mm/92

### Loadout Options

N/A

### Other Changes

Originally delivered via UK lend-lease as gunboats. Renamed TČ101 - 107 after formal transfer to Yugoslavia in 1945.

Late 1945, all: had 2x 450mm TT installed.

### Sources

https://www.navypedia.org/ships/yugoslavia/yu_cf_pt201.htm

![image](https://user-images.githubusercontent.com/99599482/192849417-e63facf5-cdee-45a4-b02a-4db70276d29c.png)

**Comment by PygmalionOfCyprus** [comment] 2022-11-08 18:13
Duplicate of #2260

**Closed by PygmalionOfCyprus** 2022-11-08 18:13 UTC
Labels: CWDB, ship, copy
