### ISSUE TITLE
CM501GA NLOS Missile

### ISSUE THREAD

**Issue by Siegemiester** [PygmalionOfCyprus/cmo-db-requests#4453] opened 2024-04-03 09:45 UTC
### DB Selector

DB3K

### Baseline

2788 (Spike NLOS)

### Hypothetical

No

### Name

CM501GA

### Length (m)

2

### Width/Span (m)

1?

### Diameter (m)

0.18

### Weight (kg)

100

### Range (nm)

21

### Warhead

20kg HE (or HEDP?)

### Targets

Surface Vessel, Land Structure - Soft, Land Structure - Hardened, Radar, Mobile Target - Soft, Mobile Target - Hardened, Mobile Target - Personnel

### CEP (m)

1m

### Sensors

1x TV Camera
1x FLIR Camera
2 Way Datalink for midcourse guidance

### Weapon Codes

Lock-On After Launch (LOAL), Terrain Following, Weapon - INS Navigation, Uses BeiDou/COMPASS

### Comments

The CM501GA is a very recent chinese 'No Line of Sight' ground attack munition modelled off a proposed NLOS missile design from 2012 (the CM501G) Which itself was modelled off the discontinued US NLOS-Netfire program

https://en.wikipedia.org/wiki/CM-501G

![DIMDEX_2024_CM-501GA_925_001](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/160735116/16076d20-8bd9-4202-94c2-f8d4b131895d)

According to 
https://armyrecognition.com/defense_news_march_2024_global_security_army_industry/china_promotes_new_cm-501ga_lightweight_multi-purpose_missile_at_dimdex_2024.html

"the CM-501GA non-line-of-sight (NLOS) anti-tank missile. This model is designed to be lighter than its predecessor, the CM-501G, and is intended for use on a variety of platforms such as light vehicles, small ships, and helicopters. The missile has a reported operational range of up to 40 kilometers."

"designed to be mounted on a 6×6 vehicle platform using the Dongfeng CSK181 truck, is capable of carrying 16 NLOS missiles."

Performance & Dimensions
"The CM-501GA missile is equipped with a dual mid-course guidance system combining an inertial navigation system (INS) and a satellite datalink, alongside TV and infrared (IR) guidance for the terminal flight phase. The missile's known specifications include a length of 2 meters, a diameter of 180 mm, and a total weight of 100 kilograms, which includes a 20-kilogram high-explosive warhead, with a claimed accuracy within 1 meter and a success rate of 90%"

 "it was revealed that the PLA had started deploying these tactical missiles."
This missile is already in service with the PLA and thus is not strictly an export product

http://www.xinhuanet.com//mil/2015-05/27/c_127846853_2.htm
reports 
 "able to conduct autonomous navigation and can complete quick maneuvers and complex firing tasks in an unfamiliar landscape." Indicating some degree of terrain following and obstacle avoidance capability

"The projectiles can be quickly integrated into different combat platforms such as warships and helicopters."
meaning that this weapon is at the very least Very likely to be mounted the Z10, Z19 and upcoming Z21.

### Sources

https://en.wikipedia.org/wiki/CM-501G

https://armyrecognition.com/defense_news_march_2024_global_security_army_industry/china_promotes_new_cm-501ga_lightweight_multi-purpose_missile_at_dimdex_2024.html

http://www.xinhuanet.com//mil/2015-05/27/c_127846853_2.htm

**Comment by PygmalionOfCyprus** [comment] 2024-11-13 19:41
Duplicate of #4840

**Closed as not planned by PygmalionOfCyprus** 2024-11-13 19:41 UTC
Labels: addition, DB3K, weapon
