### ISSUE TITLE
S-3B Viking Loadout and Database Rename

### ISSUE THREAD

**Issue by 5th-Domain** [PygmalionOfCyprus/cmo-db-requests#358] opened 2022-02-22 04:41 UTC
### DB Selector

DB3K

### Affected DBID(s)

#5390, #5389, S-3B Viking Database v492

### Summary of Changes

The Loadout ASW Patrol with Mk 54 LHT Mod 0 Torpedoes is incorrectly labelled as MK50 Barracuda in both the DB Viewer and on the Weapons Loadout Select Screen.

### Sources

In game

**Comment by PygmalionOfCyprus** [comment] 2022-02-22 11:33
Which loadout? The Mk50 Barracuda loadout on the Vikings is carrying Mk50s as far as I can tell.

**Comment by 5th-Domain** [comment] 2022-02-22 21:12
There are currently two loadout described as MK 50 Barracuda but one of them is MK54 LHT Mod 0 Loadout.

**Comment by PygmalionOfCyprus** [comment] 2022-02-23 13:43
I'm still confused. 

Loadout 29892 is titled "Mk54 LHT Mod 0, AN/SSQ-53D DIFAR, AN/SSQ-62C DICASS" and correctly carries the Mk54 LHT Mod 0.

The only S-3B loadout with Mk50 Barracuda in the title is 29891, but that correctly carries the Mk50 Barracuda.

**Comment by 5th-Domain** [comment] 2022-02-23 18:50
![MK50 Barracuda](https://user-images.githubusercontent.com/99503587/155387209-771761b9-a0e1-4769-8704-4810eb2fee05.png)

**Comment by PygmalionOfCyprus** [comment] 2022-02-24 00:09
Thanks for the screenshot, that is helpful! (And thanks for the tip, @tbrandon517!)

It does look like this must have been "ninja'd" this release. Loadout names, typos, etc. have a way of getting patched up without associated tickets. Alternatively, if this was previously submitted on the old tracker, we may have hit it through that and I've just forgotten...wouldn't be the first time.

Anyway, here's what I'll do. I'm going to tentatively close this issue, because as far as I can tell the problem has been solved. We're wrapping up 493 and sending it to the wider team next week (which you may have noticed from the milestone deadline); when exactly that gets rolled into a public beta is out of my hands, so I can't give an exact ETA, but you should have a copy available sooner rather than later. If the issue is still present in 493 please holler in this thread and I'll reopen the issue as a bug.

**Closed** 2022-02-24 00:09 UTC
Labels: aircraft, DB3K, update
