### ISSUE TITLE
GLSDB

### ISSUE THREAD

**Issue by fmachanda** [PygmalionOfCyprus/cmo-db-requests#3061] opened 2023-02-20 18:12 UTC
### DB Selector

DB3K

### Baseline

484, 773

### Hypothetical

No

### Name

Ground Launched Small Diameter Bomb (GLSDB)

### Length (m)

3.91

### Width/Span (m)

1.61

### Diameter (m)

0.24

### Weight (kg)

272.16

### Range (nm)

81.0

### Warhead

22.7kg HE

### Targets

Land Structure - Soft, Land Structure - Hardened, Runway

### CEP (m)

10

### Sensors

None

### Sources

https://www.saab.com/products/ground-launched-small-diameter-bomb-glsdb
https://en.wikipedia.org/wiki/Ground_Launched_Small_Diameter_Bomb
https://www.boeing.co.kr/resources/ko_KR/Seoul-International/2015/GLSDB.pdf
https://www.globalsecurity.org/military/systems/munitions/glsdb-specs.htm
https://www.globalsecurity.org/military/systems/munitions/glsdb-pics.htm
https://www.globalsecurity.org/military/systems/munitions/glsdb.htm

**Comment by tbrandon517** [comment] 2023-02-20 18:58
Duplicate of #2617

**Closed** 2023-04-07 17:44 UTC
Labels: addition, DB3K, weapon
