### ISSUE TITLE
Hermes 900 UAV Fuel and speed 

### ISSUE THREAD

**Issue by LeStefEnV11** [PygmalionOfCyprus/cmo-db-requests#3275] opened 2023-04-10 14:26 UTC
### DB Selector

DB3K

### Affected DBID(s)

Aircraft_2576, 5645, 5323, 5324, 5330, 4646, 5413, 5102, 5811, 5892

### Summary of Changes

![Screen Shot 04-10-23 at 03 21 PM](https://user-images.githubusercontent.com/130376424/230920378-d5ef033d-8b4b-4f0e-bba4-54f8ac3735ef.JPG)

Fuel consumption is not in line with speed. The uav’s autonomy is only a few minutes in "Loiter" and several hours in "Military".

### Sources

Data of the game

**Comment by PygmalionOfCyprus** [comment] 2023-04-24 19:50
Duplicate of #2569. Upgrade to DB 499.

**Closed by PygmalionOfCyprus** 2023-04-24 19:50 UTC
Labels: aircraft, DB3K, update
