### ISSUE TITLE
m30/m30a1/m30a2 gmlrs er range edit for himars or us mlrs

### ISSUE THREAD

**Issue by afrika1212** [PygmalionOfCyprus/cmo-db-requests#1568] opened 2022-07-02 00:52 UTC
### DB Selector

DB3K

### Affected DBID(s)

50, 2699, 3136

### Summary of Changes

Can we remove the 'er' from 'gmlrs er'? All dbid's above have the right range for gmlrs without the 'er' at 45nm. gmlrs er came out in 2021 after the dbid entries above and is 93nm. it would be nice to have 'gmlrs er' as well but that would be a new entry. database db3000 v 493, v1.04, build 1147.45.

### Sources

army website 
https://asc.army.mil/web/portfolio-item/guided-multiple-launch-rocket-system-gmlrs-dpicmunitaryalternative-warhead/

wikipedia 
https://en.wikipedia.org/wiki/M270_Multiple_Launch_Rocket_System#GMLRS

forbes
https://www.forbes.com/sites/sebastienroblin/2022/05/31/biden-decoded-ukraine-will-get-us-rocket-systems-but-not-long-range-missiles/?sh=1592c33fa389

**Comment by PygmalionOfCyprus** [comment] 2022-07-02 03:06
Duplicate of #1519

**Closed by PygmalionOfCyprus** 2022-07-02 03:06 UTC
Labels: DB3K, update

**Comment by afrika1212** [comment] 2022-07-02 11:14
oh didnt know it was entered already
