### ISSUE TITLE
Add Georgia Ayety (PC)

### ISSUE THREAD

**Issue by Parel803** [PygmalionOfCyprus/cmo-db-requests#2133] opened 2022-09-03 08:08 UTC
### DB Selector

DB3K

### DBID to Copy

CWDB #844 

### Hypothetical

No

### Name

Patrol Craft, P22, Ayeti

### Country

Georgia

### Service

Coastguard

### In Commission

DEU 1960-1998, GEO 1998-2008

### Number in Service

1

### Sensors

Delete KH 14/9
Add SPS-64 radar
Add 193M sonar (src2), src1 states no MCM capabilities after refit in DEU

### Mounts

Add 2x single 12.7 MG
Add PAP104 USV (src2), src1 states no MCM capabilities after refit in DEU

### Other Changes

Length - 47.1
2x MTU MD diesels

* ex-Minden M1085 (DEU)

### Sources

1: JFS 2002-2003
2: https://www.navypedia.org/ships/georgia/geo_cg_ayeti.htm

**Comment by PygmalionOfCyprus** [comment] 2023-10-10 17:53
Duplicate of #1082

**Closed by PygmalionOfCyprus** 2023-10-10 17:53 UTC
Labels: DB3K, ship, copy, DBTwools
