### ISSUE TITLE
Super Hornet Block III Air Launched SM-6 AAW/ASUW

### ISSUE THREAD

**Issue by tbrandon517** [PygmalionOfCyprus/cmo-db-requests#1658] opened 2022-07-08 13:16 UTC
### DB Selector

DB3K

### User(s)

USN Block III F/A-18s

### Weapons Carried

-2x CFTs
-4x SM-6 Dual II (w/o booster) 
-6x AIM-120D 
-1x Centerline tank w/ IRST-21

### Requires Buddy Illumination

No

### Default Combat Radius (nm)

510

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

No

### Comments

Hypothetical loadout for BLK III F/A-18 for Long Range Anti Air Warfare or ASuW strike.

### Sources

https://www.realcleardefense.com/articles/2018/03/01/giving_the_super_hornet_more_punch_think_sm-6_113137.html
https://aviationweek.com/defense-space/missile-defense-weapons/weekly-debrief-air-launched-sm-6-missile-exposed-new-test?fbclid=IwAR0sCOvL5tv0aQLSxJfgBNGnmyUWIHNBQxvtUjUonhd4E2K9fEMUwtAX2XI

![image](https://user-images.githubusercontent.com/99599482/177999418-5c1a662b-94a4-4a89-b080-7a230ca746a7.png)

**Comment by tbrandon517** [comment] 2024-06-04 20:00
Updated

https://www.twz.com/sea/super-hornet-armed-with-sm-6-missile-spotted-over-california?fbclid=IwZXh0bgNhZW0CMTEAAR2OYxhaeYmvrbiAtZ9fmLj10sBqd9YzgtsumsDwY_N4dGrcW3IRLY5dksY_aem_ATLy3maLne8ahUwCLJV43t-q_fbjoLt8BS-XGNl28GQGu8aX_FILJEu1zrjSp4NnUzgfJq1nVS8V1zwjM0__hIgm

**Comment by tbrandon517** [comment] 2024-06-04 20:06
More

https://www.navalnews.com/naval-news/2024/06/air-launched-sm-6-spotted-again-on-f-a-18-super-hornet/?fbclid=IwZXh0bgNhZW0CMTEAAR0sMZWPZcXkZLl9icyNQXyIKJVSvZZPzVvpnlMeD7VsGA3FHhPkmnOQTes_aem_ATIZ1wIXnBhqNsUSsCG5tA2817J1I1ITL1lZNB5D9Rgf_vqB87iIBrvl05Go3dluwh5B5l2GwApzd_xZ-qX30Ugv

**Comment by tbrandon517** [comment] 2024-06-04 21:34
Related #4612

**Comment by tbrandon517** [comment] 2024-06-06 21:07
Additional 

https://theaviationist.com/2024/06/04/u-s-navy-super-hornet-with-sm-6/

**Comment by LuigiP57** [comment] 2024-07-03 08:01
![image](https://github.com/PygmalionOfCyprus/cmo-db-requests/assets/107970049/45157462-a07f-4915-b559-153930954035)
credit to @ John Ridge (on X)

Seems like its name is **XAIM-174B**. Supposing a hornet could carry 2/4 of this. I think **more loadout options** are needed.

**Comment by tbrandon517** [comment] 2024-07-03 12:56
Additional 

https://www.twz.com/air/aim-174-super-hornet-launched-variant-of-sm-6-missile-breaks-cover-in-hawaii?fbclid=IwZXh0bgNhZW0CMTEAAR36YgIPkCRLKoqlAUX2kTlgecqSxohmktMvMXLA0BiQbZoQs0GlydiTQGM_aem_4lbgzTEQWrXJEQQIgkS5ng

**Comment by tbrandon517** [comment] 2024-07-05 18:46
Operationally Deployed 

https://www.navalnews.com/naval-news/2024/07/u-s-navy-confirms-sm-6-air-launched-configuration-is-operationally-deployed/?fbclid=IwZXh0bgNhZW0CMTEAAR3k0OCp7QRakD-qoAY5f10W0J8qI2hfCi-cEUoqR7pFed3XP0ckBLZU5wY_aem_9C6NTWVB8LZuK5FtkwMzGw

**Comment by tbrandon517** [comment] 2024-07-07 22:51
"At its surface-to-air published range, the SM-6 achieves ranges of 130 nmi (240 km) with even higher estimated ranges up to 250 nmi (463 km). An air-launched variant would dramatically increase that range, giving a Carrier Air Wing (CAW) more reach to defeat distant targets."

250 nmi 😳

https://www.navalnews.com/naval-news/2024/06/air-launched-sm-6-spotted-again-on-f-a-18-super-hornet/

**Comment by PygmalionOfCyprus** [comment] 2024-07-08 18:54
Duplicate of #4704

**Comment by PygmalionOfCyprus** [comment] 2024-07-08 18:54
(I know you were first, there's just more data/discussion happening on the newer thread so in the interest of consolidation I say we move there.)

**Closed by PygmalionOfCyprus** 2024-07-08 18:54 UTC
Labels: DB3K, loadout

**Comment by tbrandon517** [comment] 2024-07-08 22:16
> (I know you were first, there's just more data/discussion happening on the newer thread so in the interest of consolidation I say we move there.)

No worries. I think there is one other closed thread as well but all of them are tagged/linked and I have copied anything new across all of them. Totally understandable mine from 2022 would get lost in time when all the new sightings and news broke recently.

**Comment by Luigi-II** [comment] 2024-09-11 04:24
ANNNNNNND, Ladies and gentlemen:
https://twitter.com/John_A_Ridge/status/1833684592554861009
![image](https://github.com/user-attachments/assets/9c0f41ae-d316-46ce-ad5a-a3f0392744b6)
(If it's not photoshopped)

**Comment by tbrandon517** [comment] 2024-09-11 10:54
> ANNNNNNND, Ladies and gentlemen: https://twitter.com/John_A_Ridge/status/1833684592554861009 ![image](https://private-user-images.githubusercontent.com/178719098/366297063-9c0f41ae-d316-46ce-ad5a-a3f0392744b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwNTIyODAsIm5iZiI6MTcyNjA1MTk4MCwicGF0aCI6Ii8xNzg3MTkwOTgvMzY2Mjk3MDYzLTljMGY0MWFlLWQzMTYtNDZjZS1hZDVhLWEzZjAzOTI3NDRiNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMVQxMDUzMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MmQ5NGM5NGYxN2Q4NWUwY2MwNGViNzRkNWJjOGFiZGY2MjY2MDdjYjAzNzE0OGJmYjc0OGFhNGE2Y2VmNzliJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.S4XQEKxg835XeJSAMhvO4FLbM2ptcd4O55vF9vGLFRU) (If it's not photoshopped)

Those Real Clear Defense guys got pretty close years ago.
