### ISSUE TITLE
China, H-6N Badger, Loadout request

### ISSUE THREAD

**Issue by LuigiP57** [PygmalionOfCyprus/cmo-db-requests#1932] opened 2022-07-29 13:53 UTC
### DB Selector

DB3K

### User(s)

Aircraft 4837, 4969

### Weapons Carried

New loadouts added: 
6x KD/CJ-20
4x KD-63
4x YJ-12 + 2x KG-800 ECM Pod
(same as H-6K)

### Requires Buddy Illumination

No

### Weather Restrictions

All-Weather

### Time-of-Day Restrictions

Day & Night

### Capable of Quick Turnaround

Yes

### Sources

![image](https://user-images.githubusercontent.com/107970049/181773953-04f47e7d-410f-4410-b594-a14962be883e.png)
![image](https://user-images.githubusercontent.com/107970049/181774132-60043211-56e5-417e-9004-be194829aa9f.png)
ECM Pod on other Badgers
![image](https://user-images.githubusercontent.com/107970049/181774902-51b01102-ef66-4055-819f-f79cda716986.png)

**Comment by PygmalionOfCyprus** [comment] 2022-08-05 08:00
Duplicate of a ticket in the private tracker, handled 496.

**Closed by PygmalionOfCyprus** 2022-08-05 08:00 UTC
Labels: DB3K, loadout
